// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hex_boosting.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface boosted_hex_update_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.boosted_hex_update_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unix timestamp in seconds the hex was updated
   * </pre>
   *
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * Details of the updated hex
   * </pre>
   *
   * <code>.helium.boosted_hex_info_v1 update = 2;</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <pre>
   * Details of the updated hex
   * </pre>
   *
   * <code>.helium.boosted_hex_info_v1 update = 2;</code>
   * @return The update.
   */
  com.helium.grpc.mobile.boosted_hex_info_v1 getUpdate();
  /**
   * <pre>
   * Details of the updated hex
   * </pre>
   *
   * <code>.helium.boosted_hex_info_v1 update = 2;</code>
   */
  com.helium.grpc.mobile.boosted_hex_info_v1OrBuilder getUpdateOrBuilder();
}
