// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hex_boosting.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface boosted_hex_info_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.boosted_hex_info_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The res12 h3 index of the boosted hex
   * </pre>
   *
   * <code>uint64 location = 1;</code>
   * @return The location.
   */
  long getLocation();

  /**
   * <pre>
   * Unix timestamp in seconds of the start of the boost period
   * 0 if the boosting has not yet started
   * </pre>
   *
   * <code>uint64 start_ts = 2;</code>
   * @return The startTs.
   */
  long getStartTs();

  /**
   * <pre>
   * Unix timestamp in seconds of the end of the boost period
   * 0 if the boosting has not yet started
   * </pre>
   *
   * <code>uint64 end_ts = 3;</code>
   * @return The endTs.
   */
  long getEndTs();

  /**
   * <pre>
   * The length of the boost period in months expressed as seconds
   * where one month = 30 days
   * </pre>
   *
   * <code>uint32 period_length = 4;</code>
   * @return The periodLength.
   */
  int getPeriodLength();

  /**
   * <pre>
   * the multipliers valid for this hex
   * for each period
   * </pre>
   *
   * <code>repeated uint32 multipliers = 5;</code>
   * @return A list containing the multipliers.
   */
  java.util.List<java.lang.Integer> getMultipliersList();
  /**
   * <pre>
   * the multipliers valid for this hex
   * for each period
   * </pre>
   *
   * <code>repeated uint32 multipliers = 5;</code>
   * @return The count of multipliers.
   */
  int getMultipliersCount();
  /**
   * <pre>
   * the multipliers valid for this hex
   * for each period
   * </pre>
   *
   * <code>repeated uint32 multipliers = 5;</code>
   * @param index The index of the element to return.
   * @return The multipliers at the given index.
   */
  int getMultipliers(int index);

  /**
   * <pre>
   * the onchain address of the boosted hex account
   * </pre>
   *
   * <code>bytes boosted_hex_pubkey = 6;</code>
   * @return The boostedHexPubkey.
   */
  com.google.protobuf.ByteString getBoostedHexPubkey();

  /**
   * <pre>
   * the onchain address of the boost config account
   * </pre>
   *
   * <code>bytes boost_config_pubkey = 7;</code>
   * @return The boostConfigPubkey.
   */
  com.google.protobuf.ByteString getBoostConfigPubkey();

  /**
   * <code>uint32 version = 8;</code>
   * @return The version.
   */
  int getVersion();
}
