// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface coverage_object_req_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.coverage_object_req_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes pub_key = 1;</code>
   * @return The pubKey.
   */
  com.google.protobuf.ByteString getPubKey();

  /**
   * <code>bytes uuid = 2;</code>
   * @return The uuid.
   */
  com.google.protobuf.ByteString getUuid();

  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 3;</code>
   * @return Whether the cbsdId field is set.
   */
  boolean hasCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 3;</code>
   * @return The cbsdId.
   */
  java.lang.String getCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 3;</code>
   * @return The bytes for cbsdId.
   */
  com.google.protobuf.ByteString
      getCbsdIdBytes();

  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 4;</code>
   * @return Whether the hotspotKey field is set.
   */
  boolean hasHotspotKey();
  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 4;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <pre>
   * Timestamp in seconds since the unix epoch indicating the start of coverage
   * </pre>
   *
   * <code>uint64 coverage_claim_time = 5;</code>
   * @return The coverageClaimTime.
   */
  long getCoverageClaimTime();

  /**
   * <code>repeated .helium.poc_mobile.radio_hex_signal_level coverage = 6;</code>
   */
  java.util.List<com.helium.grpc.mobile.radio_hex_signal_level> 
      getCoverageList();
  /**
   * <code>repeated .helium.poc_mobile.radio_hex_signal_level coverage = 6;</code>
   */
  com.helium.grpc.mobile.radio_hex_signal_level getCoverage(int index);
  /**
   * <code>repeated .helium.poc_mobile.radio_hex_signal_level coverage = 6;</code>
   */
  int getCoverageCount();
  /**
   * <code>repeated .helium.poc_mobile.radio_hex_signal_level coverage = 6;</code>
   */
  java.util.List<? extends com.helium.grpc.mobile.radio_hex_signal_levelOrBuilder> 
      getCoverageOrBuilderList();
  /**
   * <code>repeated .helium.poc_mobile.radio_hex_signal_level coverage = 6;</code>
   */
  com.helium.grpc.mobile.radio_hex_signal_levelOrBuilder getCoverageOrBuilder(
      int index);

  /**
   * <code>bool indoor = 7;</code>
   * @return The indoor.
   */
  boolean getIndoor();

  /**
   * <pre>
   * Trust score (0.0 - 1.0) multiplied by 1000
   * </pre>
   *
   * <code>uint32 trust_score = 8;</code>
   * @return The trustScore.
   */
  int getTrustScore();

  /**
   * <code>bytes signature = 9;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  com.helium.grpc.mobile.coverage_object_req_v1.KeyTypeCase getKeyTypeCase();
}
