// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

/**
 * Protobuf type {@code helium.poc_mobile.data_transfer_session_req_v1}
 */
public final class data_transfer_session_req_v1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helium.poc_mobile.data_transfer_session_req_v1)
    data_transfer_session_req_v1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      data_transfer_session_req_v1.class.getName());
  }
  // Use data_transfer_session_req_v1.newBuilder() to construct.
  private data_transfer_session_req_v1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private data_transfer_session_req_v1() {
    pubKey_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_data_transfer_session_req_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.mobile.data_transfer_session_req_v1.class, com.helium.grpc.mobile.data_transfer_session_req_v1.Builder.class);
  }

  private int bitField0_;
  public static final int DATA_TRANSFER_USAGE_FIELD_NUMBER = 1;
  private com.helium.grpc.mobile.data_transfer_event dataTransferUsage_;
  /**
   * <pre>
   * &#47; data_transfer_event represents traffic usage happening on a hotspot
   * / it is traffic quota or timer based
   * / it is securely created and signed by hotspot
   * </pre>
   *
   * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
   * @return Whether the dataTransferUsage field is set.
   */
  @java.lang.Override
  public boolean hasDataTransferUsage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * &#47; data_transfer_event represents traffic usage happening on a hotspot
   * / it is traffic quota or timer based
   * / it is securely created and signed by hotspot
   * </pre>
   *
   * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
   * @return The dataTransferUsage.
   */
  @java.lang.Override
  public com.helium.grpc.mobile.data_transfer_event getDataTransferUsage() {
    return dataTransferUsage_ == null ? com.helium.grpc.mobile.data_transfer_event.getDefaultInstance() : dataTransferUsage_;
  }
  /**
   * <pre>
   * &#47; data_transfer_event represents traffic usage happening on a hotspot
   * / it is traffic quota or timer based
   * / it is securely created and signed by hotspot
   * </pre>
   *
   * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
   */
  @java.lang.Override
  public com.helium.grpc.mobile.data_transfer_eventOrBuilder getDataTransferUsageOrBuilder() {
    return dataTransferUsage_ == null ? com.helium.grpc.mobile.data_transfer_event.getDefaultInstance() : dataTransferUsage_;
  }

  public static final int REWARD_CANCELLED_FIELD_NUMBER = 2;
  private boolean rewardCancelled_ = false;
  /**
   * <pre>
   * &#47; this decision is done by OCS like system
   * </pre>
   *
   * <code>bool reward_cancelled = 2;</code>
   * @return The rewardCancelled.
   */
  @java.lang.Override
  public boolean getRewardCancelled() {
    return rewardCancelled_;
  }

  public static final int PUB_KEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * &#47; Online Charging System is part of teleco stack which is able
   * / to make a decision about data transfer and reward
   * </pre>
   *
   * <code>bytes pub_key = 3;</code>
   * @return The pubKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPubKey() {
    return pubKey_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  public static final int REWARDABLE_BYTES_FIELD_NUMBER = 5;
  private long rewardableBytes_ = 0L;
  /**
   * <code>uint64 rewardable_bytes = 5;</code>
   * @return The rewardableBytes.
   */
  @java.lang.Override
  public long getRewardableBytes() {
    return rewardableBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDataTransferUsage());
    }
    if (rewardCancelled_ != false) {
      output.writeBool(2, rewardCancelled_);
    }
    if (!pubKey_.isEmpty()) {
      output.writeBytes(3, pubKey_);
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(4, signature_);
    }
    if (rewardableBytes_ != 0L) {
      output.writeUInt64(5, rewardableBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDataTransferUsage());
    }
    if (rewardCancelled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, rewardCancelled_);
    }
    if (!pubKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, pubKey_);
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, signature_);
    }
    if (rewardableBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, rewardableBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.mobile.data_transfer_session_req_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.mobile.data_transfer_session_req_v1 other = (com.helium.grpc.mobile.data_transfer_session_req_v1) obj;

    if (hasDataTransferUsage() != other.hasDataTransferUsage()) return false;
    if (hasDataTransferUsage()) {
      if (!getDataTransferUsage()
          .equals(other.getDataTransferUsage())) return false;
    }
    if (getRewardCancelled()
        != other.getRewardCancelled()) return false;
    if (!getPubKey()
        .equals(other.getPubKey())) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (getRewardableBytes()
        != other.getRewardableBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDataTransferUsage()) {
      hash = (37 * hash) + DATA_TRANSFER_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getDataTransferUsage().hashCode();
    }
    hash = (37 * hash) + REWARD_CANCELLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRewardCancelled());
    hash = (37 * hash) + PUB_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getPubKey().hashCode();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (37 * hash) + REWARDABLE_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRewardableBytes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.mobile.data_transfer_session_req_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.mobile.data_transfer_session_req_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.poc_mobile.data_transfer_session_req_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.poc_mobile.data_transfer_session_req_v1)
      com.helium.grpc.mobile.data_transfer_session_req_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_data_transfer_session_req_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.mobile.data_transfer_session_req_v1.class, com.helium.grpc.mobile.data_transfer_session_req_v1.Builder.class);
    }

    // Construct using com.helium.grpc.mobile.data_transfer_session_req_v1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDataTransferUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dataTransferUsage_ = null;
      if (dataTransferUsageBuilder_ != null) {
        dataTransferUsageBuilder_.dispose();
        dataTransferUsageBuilder_ = null;
      }
      rewardCancelled_ = false;
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      rewardableBytes_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.mobile.data_transfer_session_req_v1 getDefaultInstanceForType() {
      return com.helium.grpc.mobile.data_transfer_session_req_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.mobile.data_transfer_session_req_v1 build() {
      com.helium.grpc.mobile.data_transfer_session_req_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.mobile.data_transfer_session_req_v1 buildPartial() {
      com.helium.grpc.mobile.data_transfer_session_req_v1 result = new com.helium.grpc.mobile.data_transfer_session_req_v1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.helium.grpc.mobile.data_transfer_session_req_v1 result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dataTransferUsage_ = dataTransferUsageBuilder_ == null
            ? dataTransferUsage_
            : dataTransferUsageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rewardCancelled_ = rewardCancelled_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pubKey_ = pubKey_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.signature_ = signature_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rewardableBytes_ = rewardableBytes_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.mobile.data_transfer_session_req_v1) {
        return mergeFrom((com.helium.grpc.mobile.data_transfer_session_req_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.mobile.data_transfer_session_req_v1 other) {
      if (other == com.helium.grpc.mobile.data_transfer_session_req_v1.getDefaultInstance()) return this;
      if (other.hasDataTransferUsage()) {
        mergeDataTransferUsage(other.getDataTransferUsage());
      }
      if (other.getRewardCancelled() != false) {
        setRewardCancelled(other.getRewardCancelled());
      }
      if (other.getPubKey() != com.google.protobuf.ByteString.EMPTY) {
        setPubKey(other.getPubKey());
      }
      if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
        setSignature(other.getSignature());
      }
      if (other.getRewardableBytes() != 0L) {
        setRewardableBytes(other.getRewardableBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDataTransferUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              rewardCancelled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              pubKey_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              rewardableBytes_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.helium.grpc.mobile.data_transfer_event dataTransferUsage_;
    private com.google.protobuf.SingleFieldBuilder<
        com.helium.grpc.mobile.data_transfer_event, com.helium.grpc.mobile.data_transfer_event.Builder, com.helium.grpc.mobile.data_transfer_eventOrBuilder> dataTransferUsageBuilder_;
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     * @return Whether the dataTransferUsage field is set.
     */
    public boolean hasDataTransferUsage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     * @return The dataTransferUsage.
     */
    public com.helium.grpc.mobile.data_transfer_event getDataTransferUsage() {
      if (dataTransferUsageBuilder_ == null) {
        return dataTransferUsage_ == null ? com.helium.grpc.mobile.data_transfer_event.getDefaultInstance() : dataTransferUsage_;
      } else {
        return dataTransferUsageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public Builder setDataTransferUsage(com.helium.grpc.mobile.data_transfer_event value) {
      if (dataTransferUsageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataTransferUsage_ = value;
      } else {
        dataTransferUsageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public Builder setDataTransferUsage(
        com.helium.grpc.mobile.data_transfer_event.Builder builderForValue) {
      if (dataTransferUsageBuilder_ == null) {
        dataTransferUsage_ = builderForValue.build();
      } else {
        dataTransferUsageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public Builder mergeDataTransferUsage(com.helium.grpc.mobile.data_transfer_event value) {
      if (dataTransferUsageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          dataTransferUsage_ != null &&
          dataTransferUsage_ != com.helium.grpc.mobile.data_transfer_event.getDefaultInstance()) {
          getDataTransferUsageBuilder().mergeFrom(value);
        } else {
          dataTransferUsage_ = value;
        }
      } else {
        dataTransferUsageBuilder_.mergeFrom(value);
      }
      if (dataTransferUsage_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public Builder clearDataTransferUsage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dataTransferUsage_ = null;
      if (dataTransferUsageBuilder_ != null) {
        dataTransferUsageBuilder_.dispose();
        dataTransferUsageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public com.helium.grpc.mobile.data_transfer_event.Builder getDataTransferUsageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDataTransferUsageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    public com.helium.grpc.mobile.data_transfer_eventOrBuilder getDataTransferUsageOrBuilder() {
      if (dataTransferUsageBuilder_ != null) {
        return dataTransferUsageBuilder_.getMessageOrBuilder();
      } else {
        return dataTransferUsage_ == null ?
            com.helium.grpc.mobile.data_transfer_event.getDefaultInstance() : dataTransferUsage_;
      }
    }
    /**
     * <pre>
     * &#47; data_transfer_event represents traffic usage happening on a hotspot
     * / it is traffic quota or timer based
     * / it is securely created and signed by hotspot
     * </pre>
     *
     * <code>.helium.poc_mobile.data_transfer_event data_transfer_usage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.helium.grpc.mobile.data_transfer_event, com.helium.grpc.mobile.data_transfer_event.Builder, com.helium.grpc.mobile.data_transfer_eventOrBuilder> 
        getDataTransferUsageFieldBuilder() {
      if (dataTransferUsageBuilder_ == null) {
        dataTransferUsageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.helium.grpc.mobile.data_transfer_event, com.helium.grpc.mobile.data_transfer_event.Builder, com.helium.grpc.mobile.data_transfer_eventOrBuilder>(
                getDataTransferUsage(),
                getParentForChildren(),
                isClean());
        dataTransferUsage_ = null;
      }
      return dataTransferUsageBuilder_;
    }

    private boolean rewardCancelled_ ;
    /**
     * <pre>
     * &#47; this decision is done by OCS like system
     * </pre>
     *
     * <code>bool reward_cancelled = 2;</code>
     * @return The rewardCancelled.
     */
    @java.lang.Override
    public boolean getRewardCancelled() {
      return rewardCancelled_;
    }
    /**
     * <pre>
     * &#47; this decision is done by OCS like system
     * </pre>
     *
     * <code>bool reward_cancelled = 2;</code>
     * @param value The rewardCancelled to set.
     * @return This builder for chaining.
     */
    public Builder setRewardCancelled(boolean value) {

      rewardCancelled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; this decision is done by OCS like system
     * </pre>
     *
     * <code>bool reward_cancelled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRewardCancelled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rewardCancelled_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * &#47; Online Charging System is part of teleco stack which is able
     * / to make a decision about data transfer and reward
     * </pre>
     *
     * <code>bytes pub_key = 3;</code>
     * @return The pubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }
    /**
     * <pre>
     * &#47; Online Charging System is part of teleco stack which is able
     * / to make a decision about data transfer and reward
     * </pre>
     *
     * <code>bytes pub_key = 3;</code>
     * @param value The pubKey to set.
     * @return This builder for chaining.
     */
    public Builder setPubKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      pubKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; Online Charging System is part of teleco stack which is able
     * / to make a decision about data transfer and reward
     * </pre>
     *
     * <code>bytes pub_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPubKey() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pubKey_ = getDefaultInstance().getPubKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature = 4;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>bytes signature = 4;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000008);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    private long rewardableBytes_ ;
    /**
     * <code>uint64 rewardable_bytes = 5;</code>
     * @return The rewardableBytes.
     */
    @java.lang.Override
    public long getRewardableBytes() {
      return rewardableBytes_;
    }
    /**
     * <code>uint64 rewardable_bytes = 5;</code>
     * @param value The rewardableBytes to set.
     * @return This builder for chaining.
     */
    public Builder setRewardableBytes(long value) {

      rewardableBytes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 rewardable_bytes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRewardableBytes() {
      bitField0_ = (bitField0_ & ~0x00000010);
      rewardableBytes_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helium.poc_mobile.data_transfer_session_req_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.poc_mobile.data_transfer_session_req_v1)
  private static final com.helium.grpc.mobile.data_transfer_session_req_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.mobile.data_transfer_session_req_v1();
  }

  public static com.helium.grpc.mobile.data_transfer_session_req_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<data_transfer_session_req_v1>
      PARSER = new com.google.protobuf.AbstractParser<data_transfer_session_req_v1>() {
    @java.lang.Override
    public data_transfer_session_req_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<data_transfer_session_req_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<data_transfer_session_req_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.mobile.data_transfer_session_req_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

