// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface file_infoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.file_info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.helium.poc_mobile.file_type file_type = 2;</code>
   * @return The enum numeric value on the wire for fileType.
   */
  int getFileTypeValue();
  /**
   * <code>.helium.poc_mobile.file_type file_type = 2;</code>
   * @return The fileType.
   */
  com.helium.grpc.mobile.file_type getFileType();

  /**
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>uint64 size = 4;</code>
   * @return The size.
   */
  long getSize();
}
