// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapper.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc.mobile;

public interface mapper_gps_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.mapper_gps_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unix time in seconds
   * </pre>
   *
   * <code>uint32 unix_time = 1;</code>
   * @return The unixTime.
   */
  int getUnixTime();

  /**
   * <pre>
   * Latitude of the current base station in units of 0.25 sec.
   * </pre>
   *
   * <code>int32 lat = 2;</code>
   * @return The lat.
   */
  int getLat();

  /**
   * <pre>
   * Longitude of the current base station in units of 0.25 sec.
   * </pre>
   *
   * <code>int32 lon = 3;</code>
   * @return The lon.
   */
  int getLon();

  /**
   * <pre>
   * Horizontal dilution of position in units of 0.01 HDOP.
   * </pre>
   *
   * <code>uint32 hdop = 4;</code>
   * @return The hdop.
   */
  int getHdop();

  /**
   * <pre>
   * Altitude in units of 0.25m above the WGS 84 reference ellipsoid.
   * </pre>
   *
   * <code>int64 altitude = 5;</code>
   * @return The altitude.
   */
  long getAltitude();

  /**
   * <code>int32 num_sats = 6;</code>
   * @return The numSats.
   */
  int getNumSats();

  /**
   * <pre>
   * Speed in speed in 0.25m/s per second.
   * </pre>
   *
   * <code>uint32 speed = 7;</code>
   * @return The speed.
   */
  int getSpeed();
}
