// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_mobile.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc.mobile;

public final class PocMobile {
  private PocMobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_speedtest_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_speedtest_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_speedtest_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_speedtest_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_speedtest_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_speedtest_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_verified_speedtest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_verified_speedtest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_cell_heartbeat_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_cell_heartbeat_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_cell_heartbeat_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_cell_heartbeat_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_cell_heartbeat_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_cell_heartbeat_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_wifi_heartbeat_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_wifi_heartbeat_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_wifi_heartbeat_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_wifi_heartbeat_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_wifi_heartbeat_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_wifi_heartbeat_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_mapper_attach_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_mapper_attach_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_subscriber_location_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_subscriber_location_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_subscriber_location_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_subscriber_location_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_subscriber_location_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_subscriber_location_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_threshold_report_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_threshold_report_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_threshold_report_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_threshold_report_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_threshold_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_threshold_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_verified_radio_threshold_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_verified_radio_threshold_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_invalidated_radio_threshold_report_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_invalidated_radio_threshold_report_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_invalidated_radio_threshold_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_invalidated_radio_threshold_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_verified_invalidated_radio_threshold_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_verified_invalidated_radio_threshold_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_hex_signal_level_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_hex_signal_level_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_coverage_object_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_coverage_object_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_coverage_object_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_coverage_object_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_coverage_object_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_coverage_object_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_verified_subscriber_location_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_verified_subscriber_location_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_file_info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_file_info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_processed_files_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_processed_files_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_coverage_object_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_coverage_object_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_seniority_update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_seniority_update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_speedtest_avg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_speedtest_avg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_speedtest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_speedtest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_reward_share_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_reward_share_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_radio_reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_radio_reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_boosted_hex_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_boosted_hex_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_gateway_reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_gateway_reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_subscriber_reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_subscriber_reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_service_provider_reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_service_provider_reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_unallocated_reward_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_unallocated_reward_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_mobile_reward_share_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_mobile_reward_share_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_data_transfer_session_req_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_data_transfer_event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_data_transfer_event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_data_transfer_session_resp_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_data_transfer_session_resp_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_data_transfer_session_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_data_transfer_session_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_invalid_data_transfer_ingest_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_invalid_data_transfer_ingest_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_oracle_boosting_report_v1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_oracle_boosting_report_v1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helium_poc_mobile_oracle_boosting_hex_assignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helium_poc_mobile_oracle_boosting_hex_assignment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030service/poc_mobile.proto\022\021helium.poc_m" +
      "obile\032\014mapper.proto\032\022hex_boosting.proto\032" +
      "\026service_provider.proto\"\230\001\n\020speedtest_re" +
      "q_v1\022\017\n\007pub_key\030\001 \001(\014\022\016\n\006serial\030\002 \001(\t\022\021\n" +
      "\ttimestamp\030\003 \001(\004\022\024\n\014upload_speed\030\004 \001(\004\022\026" +
      "\n\016download_speed\030\005 \001(\004\022\017\n\007latency\030\006 \001(\r\022" +
      "\021\n\tsignature\030\007 \001(\014\"\037\n\021speedtest_resp_v1\022" +
      "\n\n\002id\030\001 \001(\t\"m\n\032speedtest_ingest_report_v" +
      "1\022\032\n\022received_timestamp\030\001 \001(\004\0223\n\006report\030" +
      "\002 \001(\0132#.helium.poc_mobile.speedtest_req_" +
      "v1\"\250\001\n\022verified_speedtest\022=\n\006report\030\001 \001(" +
      "\0132-.helium.poc_mobile.speedtest_ingest_r" +
      "eport_v1\022@\n\006result\030\002 \001(\01620.helium.poc_mo" +
      "bile.speedtest_verification_result\022\021\n\tti" +
      "mestamp\030\003 \001(\004\"\350\001\n\025cell_heartbeat_req_v1\022" +
      "\017\n\007pub_key\030\001 \001(\014\022\024\n\014hotspot_type\030\002 \001(\t\022\017" +
      "\n\007cell_id\030\003 \001(\r\022\021\n\ttimestamp\030\004 \001(\004\022\013\n\003la" +
      "t\030\005 \001(\001\022\013\n\003lon\030\006 \001(\001\022\026\n\016operation_mode\030\007" +
      " \001(\010\022\025\n\rcbsd_category\030\010 \001(\t\022\017\n\007cbsd_id\030\t" +
      " \001(\t\022\021\n\tsignature\030\n \001(\014\022\027\n\017coverage_obje" +
      "ct\030\013 \001(\014\"$\n\026cell_heartbeat_resp_v1\022\n\n\002id" +
      "\030\001 \001(\t\"w\n\037cell_heartbeat_ingest_report_v" +
      "1\022\032\n\022received_timestamp\030\001 \001(\004\0228\n\006report\030" +
      "\002 \001(\0132(.helium.poc_mobile.cell_heartbeat" +
      "_req_v1\"\300\001\n\025wifi_heartbeat_req_v1\022\017\n\007pub" +
      "_key\030\001 \001(\014\022\021\n\ttimestamp\030\002 \001(\004\022\013\n\003lat\030\003 \001" +
      "(\001\022\013\n\003lon\030\004 \001(\001\022%\n\035location_validation_t" +
      "imestamp\030\005 \001(\004\022\026\n\016operation_mode\030\006 \001(\010\022\027" +
      "\n\017coverage_object\030\007 \001(\014\022\021\n\tsignature\030\010 \001" +
      "(\014\"$\n\026wifi_heartbeat_resp_v1\022\n\n\002id\030\001 \001(\t" +
      "\"w\n\037wifi_heartbeat_ingest_report_v1\022\032\n\022r" +
      "eceived_timestamp\030\001 \001(\004\0228\n\006report\030\002 \001(\0132" +
      "(.helium.poc_mobile.wifi_heartbeat_req_v" +
      "1\"c\n\036mapper_attach_ingest_report_v1\022\032\n\022r" +
      "eceived_timestamp\030\001 \001(\004\022%\n\006report\030\002 \001(\0132" +
      "\025.helium.mapper_attach\"r\n\032subscriber_loc" +
      "ation_req_v1\022\025\n\rsubscriber_id\030\001 \001(\014\022\021\n\tt" +
      "imestamp\030\002 \001(\004\022\027\n\017carrier_pub_key\030\003 \001(\014\022" +
      "\021\n\tsignature\030\004 \001(\014\")\n\033subscriber_locatio" +
      "n_resp_v1\022\n\n\002id\030\001 \001(\t\"\201\001\n$subscriber_loc" +
      "ation_ingest_report_v1\022\032\n\022received_times" +
      "tamp\030\001 \001(\004\022=\n\006report\030\002 \001(\0132-.helium.poc_" +
      "mobile.subscriber_location_req_v1\"\310\001\n\035ra" +
      "dio_threshold_report_req_v1\022\017\n\007cbsd_id\030\001" +
      " \001(\t\022\026\n\016hotspot_pubkey\030\002 \001(\014\022\027\n\017bytes_th" +
      "reshold\030\003 \001(\004\022\034\n\024subscriber_threshold\030\004 " +
      "\001(\r\022\033\n\023threshold_timestamp\030\005 \001(\004\022\027\n\017carr" +
      "ier_pub_key\030\006 \001(\014\022\021\n\tsignature\030\007 \001(\014\",\n\036" +
      "radio_threshold_report_resp_v1\022\n\n\002id\030\001 \001" +
      "(\t\"\200\001\n radio_threshold_ingest_report_v1\022" +
      "\032\n\022received_timestamp\030\001 \001(\004\022@\n\006report\030\002 " +
      "\001(\01320.helium.poc_mobile.radio_threshold_" +
      "report_req_v1\"\322\001\n)verified_radio_thresho" +
      "ld_ingest_report_v1\022C\n\006report\030\001 \001(\01323.he" +
      "lium.poc_mobile.radio_threshold_ingest_r" +
      "eport_v1\022M\n\006status\030\002 \001(\0162=.helium.poc_mo" +
      "bile.radio_threshold_report_verification" +
      "_status\022\021\n\ttimestamp\030\003 \001(\004\"\324\001\n)invalidat" +
      "ed_radio_threshold_report_req_v1\022\017\n\007cbsd" +
      "_id\030\001 \001(\t\022\026\n\016hotspot_pubkey\030\002 \001(\014\022?\n\006rea" +
      "son\030\003 \001(\0162/.helium.poc_mobile.invalidate" +
      "d_threshold_reason\022\021\n\ttimestamp\030\004 \001(\004\022\027\n" +
      "\017carrier_pub_key\030\005 \001(\014\022\021\n\tsignature\030\006 \001(" +
      "\014\"8\n*invalidated_radio_threshold_report_" +
      "resp_v1\022\n\n\002id\030\001 \001(\t\"\230\001\n,invalidated_radi" +
      "o_threshold_ingest_report_v1\022\032\n\022received" +
      "_timestamp\030\001 \001(\004\022L\n\006report\030\002 \001(\0132<.heliu" +
      "m.poc_mobile.invalidated_radio_threshold" +
      "_report_req_v1\"\366\001\n5verified_invalidated_" +
      "radio_threshold_ingest_report_v1\022O\n\006repo" +
      "rt\030\001 \001(\0132?.helium.poc_mobile.invalidated" +
      "_radio_threshold_ingest_report_v1\022Y\n\006sta" +
      "tus\030\002 \001(\0162I.helium.poc_mobile.invalidate" +
      "d_radio_threshold_report_verification_st" +
      "atus\022\021\n\ttimestamp\030\003 \001(\004\"w\n\026radio_hex_sig" +
      "nal_level\022\020\n\010location\030\001 \001(\t\0225\n\014signal_le" +
      "vel\030\002 \001(\0162\037.helium.poc_mobile.signal_lev" +
      "el\022\024\n\014signal_power\030\003 \001(\021\"\377\001\n\026coverage_ob" +
      "ject_req_v1\022\017\n\007pub_key\030\001 \001(\014\022\014\n\004uuid\030\002 \001" +
      "(\014\022\021\n\007cbsd_id\030\003 \001(\tH\000\022\025\n\013hotspot_key\030\004 \001" +
      "(\014H\000\022\033\n\023coverage_claim_time\030\005 \001(\004\022;\n\010cov" +
      "erage\030\006 \003(\0132).helium.poc_mobile.radio_he" +
      "x_signal_level\022\016\n\006indoor\030\007 \001(\010\022\023\n\013trust_" +
      "score\030\010 \001(\r\022\021\n\tsignature\030\t \001(\014B\n\n\010key_ty" +
      "pe\"%\n\027coverage_object_resp_v1\022\n\n\002id\030\001 \001(" +
      "\t\"y\n coverage_object_ingest_report_v1\022\032\n" +
      "\022received_timestamp\030\001 \001(\004\0229\n\006report\030\002 \001(" +
      "\0132).helium.poc_mobile.coverage_object_re" +
      "q_v1\"\325\001\n-verified_subscriber_location_in" +
      "gest_report_v1\022G\n\006report\030\001 \001(\01327.helium." +
      "poc_mobile.subscriber_location_ingest_re" +
      "port_v1\022H\n\006status\030\002 \001(\01628.helium.poc_mob" +
      "ile.subscriber_report_verification_statu" +
      "s\022\021\n\ttimestamp\030\003 \001(\004\"j\n\tfile_info\022\013\n\003key" +
      "\030\001 \001(\t\022/\n\tfile_type\030\002 \001(\0162\034.helium.poc_m" +
      "obile.file_type\022\021\n\ttimestamp\030\003 \001(\004\022\014\n\004si" +
      "ze\030\004 \001(\004\">\n\017processed_files\022+\n\005files\030\001 \003" +
      "(\0132\034.helium.poc_mobile.file_info\"\227\001\n\022cov" +
      "erage_object_v1\022B\n\017coverage_object\030\001 \001(\013" +
      "2).helium.poc_mobile.coverage_object_req" +
      "_v1\022=\n\010validity\030\002 \001(\0162+.helium.poc_mobil" +
      "e.coverage_object_validity\"\352\002\n\theartbeat" +
      "\022\017\n\007cbsd_id\030\001 \001(\t\022\017\n\007pub_key\030\002 \001(\014\022\035\n\021re" +
      "ward_multiplier\030\003 \001(\002B\002\030\001\022\021\n\ttimestamp\030\004" +
      " \001(\004\022/\n\tcell_type\030\005 \001(\0162\034.helium.poc_mob" +
      "ile.cell_type\0227\n\010validity\030\006 \001(\0162%.helium" +
      ".poc_mobile.heartbeat_validity\022\013\n\003lat\030\007 " +
      "\001(\001\022\013\n\003lon\030\010 \001(\001\022\027\n\017coverage_object\030\t \001(" +
      "\014\022%\n\035location_validation_timestamp\030\n \001(\004" +
      "\022\034\n\024distance_to_asserted\030\013 \001(\004\022\'\n\037locati" +
      "on_trust_score_multiplier\030\014 \001(\r\"\245\001\n\020seni" +
      "ority_update\022\021\n\007cbsd_id\030\001 \001(\tH\000\022\025\n\013hotsp" +
      "ot_key\030\002 \001(\014H\000\022\037\n\027new_seniority_timestam" +
      "p\030\003 \001(\004\022:\n\006reason\030\004 \001(\0162*.helium.poc_mob" +
      "ile.seniority_update_reasonB\n\n\010key_type\"" +
      "\223\002\n\rspeedtest_avg\022\017\n\007pub_key\030\001 \001(\014\022\034\n\024up" +
      "load_speed_avg_bps\030\002 \001(\004\022\036\n\026download_spe" +
      "ed_avg_bps\030\003 \001(\004\022\026\n\016latency_avg_ms\030\004 \001(\r" +
      "\022;\n\010validity\030\005 \001(\0162).helium.poc_mobile.s" +
      "peedtest_avg_validity\0220\n\nspeedtests\030\006 \003(" +
      "\0132\034.helium.poc_mobile.speedtest\022\021\n\ttimes" +
      "tamp\030\007 \001(\004\022\031\n\021reward_multiplier\030\010 \001(\002\"h\n" +
      "\tspeedtest\022\030\n\020upload_speed_bps\030\001 \001(\004\022\032\n\022" +
      "download_speed_bps\030\002 \001(\004\022\022\n\nlatency_ms\030\003" +
      " \001(\r\022\021\n\ttimestamp\030\004 \001(\004\"\211\001\n\022radio_reward" +
      "_share\022\021\n\towner_key\030\001 \001(\014\022\023\n\013hotspot_key" +
      "\030\002 \001(\014\022\017\n\007cbsd_id\030\003 \001(\t\022\016\n\006amount\030\004 \001(\004\022" +
      "\023\n\013start_epoch\030\005 \001(\004\022\021\n\tend_epoch\030\006 \001(\004:" +
      "\002\030\001\"\265\002\n\014radio_reward\022\023\n\013hotspot_key\030\001 \001(" +
      "\014\022\017\n\007cbsd_id\030\002 \001(\t\022\036\n\022dc_transfer_reward" +
      "\030\003 \001(\004B\002\030\001\022\022\n\npoc_reward\030\004 \001(\004\022\027\n\017covera" +
      "ge_points\030\005 \001(\004\022\033\n\023seniority_timestamp\030\006" +
      " \001(\004\022\027\n\017coverage_object\030\007 \001(\014\022\'\n\037locatio" +
      "n_trust_score_multiplier\030\010 \001(\r\022\034\n\024speedt" +
      "est_multiplier\030\t \001(\r\0225\n\rboosted_hexes\030\n " +
      "\003(\0132\036.helium.poc_mobile.boosted_hex\"3\n\013b" +
      "oosted_hex\022\020\n\010location\030\001 \001(\004\022\022\n\nmultipli" +
      "er\030\002 \001(\r\"j\n\016gateway_reward\022\023\n\013hotspot_ke" +
      "y\030\001 \001(\014\022\032\n\022dc_transfer_reward\030\002 \001(\004\022\030\n\020r" +
      "ewardable_bytes\030\003 \001(\004\022\r\n\005price\030\004 \001(\004\"M\n\021" +
      "subscriber_reward\022\025\n\rsubscriber_id\030\001 \001(\014" +
      "\022!\n\031discovery_location_amount\030\002 \001(\004\"`\n\027s" +
      "ervice_provider_reward\0225\n\023service_provid" +
      "er_id\030\001 \001(\0162\030.helium.service_provider\022\016\n" +
      "\006amount\030\002 \001(\004\"e\n\022unallocated_reward\022?\n\013r" +
      "eward_type\030\001 \001(\0162*.helium.poc_mobile.una" +
      "llocated_reward_type\022\016\n\006amount\030\002 \001(\004\"\226\003\n" +
      "\023mobile_reward_share\022\024\n\014start_period\030\001 \001" +
      "(\004\022\022\n\nend_period\030\002 \001(\004\0227\n\014radio_reward\030\003" +
      " \001(\0132\037.helium.poc_mobile.radio_rewardH\000\022" +
      ";\n\016gateway_reward\030\004 \001(\0132!.helium.poc_mob" +
      "ile.gateway_rewardH\000\022A\n\021subscriber_rewar" +
      "d\030\005 \001(\0132$.helium.poc_mobile.subscriber_r" +
      "ewardH\000\022M\n\027service_provider_reward\030\006 \001(\013" +
      "2*.helium.poc_mobile.service_provider_re" +
      "wardH\000\022C\n\022unallocated_reward\030\007 \001(\0132%.hel" +
      "ium.poc_mobile.unallocated_rewardH\000B\010\n\006r" +
      "eward\"\273\001\n\034data_transfer_session_req_v1\022C" +
      "\n\023data_transfer_usage\030\001 \001(\0132&.helium.poc" +
      "_mobile.data_transfer_event\022\030\n\020reward_ca" +
      "ncelled\030\002 \001(\010\022\017\n\007pub_key\030\003 \001(\014\022\021\n\tsignat" +
      "ure\030\004 \001(\014\022\030\n\020rewardable_bytes\030\005 \001(\004\"\366\001\n\023" +
      "data_transfer_event\022\017\n\007pub_key\030\001 \001(\014\022\024\n\014" +
      "upload_bytes\030\002 \001(\004\022\026\n\016download_bytes\030\003 \001" +
      "(\004\022Y\n\027radio_access_technology\030\004 \001(\01628.he" +
      "lium.poc_mobile.data_transfer_radio_acce" +
      "ss_technology\022\020\n\010event_id\030\005 \001(\t\022\r\n\005payer" +
      "\030\006 \001(\014\022\021\n\ttimestamp\030\007 \001(\004\022\021\n\tsignature\030\010" +
      " \001(\014\"+\n\035data_transfer_session_resp_v1\022\n\n" +
      "\002id\030\001 \001(\t\"\205\001\n&data_transfer_session_inge" +
      "st_report_v1\022\032\n\022received_timestamp\030\001 \001(\004" +
      "\022?\n\006report\030\002 \001(\0132/.helium.poc_mobile.dat" +
      "a_transfer_session_req_v1\"\365\002\n&invalid_da" +
      "ta_transfer_ingest_report_v1\022I\n\006report\030\001" +
      " \001(\01329.helium.poc_mobile.data_transfer_s" +
      "ession_ingest_report_v1\022l\n\006reason\030\002 \001(\0162" +
      "\\.helium.poc_mobile.invalid_data_transfe" +
      "r_ingest_report_v1.data_transfer_ingest_" +
      "report_status\022\021\n\ttimestamp\030\003 \001(\004\"\177\n\"data" +
      "_transfer_ingest_report_status\022\t\n\005valid\020" +
      "\000\022\r\n\tcancelled\020\001\022\027\n\023invalid_gateway_key\020" +
      "\002\022\027\n\023invalid_routing_key\020\003\022\r\n\tduplicate\020" +
      "\004\"\217\001\n\031oracle_boosting_report_v1\022\027\n\017cover" +
      "age_object\030\001 \001(\014\022F\n\013assignments\030\002 \003(\01321." +
      "helium.poc_mobile.oracle_boosting_hex_as" +
      "signment\022\021\n\ttimestamp\030\003 \001(\004\"\305\001\n\036oracle_b" +
      "oosting_hex_assignment\022\020\n\010location\030\001 \001(\t" +
      "\022\035\n\025assignment_multiplier\030\002 \001(\r\022O\n\turban" +
      "ized\030\003 \001(\0162<.helium.poc_mobile.oracle_bo" +
      "osting_hex_assignment.assignment\"!\n\nassi" +
      "gnment\022\005\n\001a\020\000\022\005\n\001b\020\001\022\005\n\001c\020\002*U\n\035speedtest" +
      "_verification_result\022\023\n\017speedtest_valid\020" +
      "\000\022\037\n\033speedtest_gateway_not_found\020\001*\252\001\n*r" +
      "adio_threshold_report_verification_statu" +
      "s\022!\n\035threshold_report_status_valid\020\000\022(\n$" +
      "threshold_report_status_legacy_valid\020\001\022/" +
      "\n+threshold_report_status_invalid_carrie" +
      "r_key\020\002*L\n\034invalidated_threshold_reason\022" +
      ",\n(invalidated_threshold_reason_radio_mo" +
      "ved\020\000*\244\001\n6invalidated_radio_threshold_re" +
      "port_verification_status\022-\n)invalidated_" +
      "threshold_report_status_valid\020\000\022;\n7inval" +
      "idated_threshold_report_status_invalid_c" +
      "arrier_key\020\001*7\n\014signal_level\022\010\n\004NONE\020\000\022\007" +
      "\n\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020\003*f\n%subscri" +
      "ber_report_verification_status\022\t\n\005valid\020" +
      "\000\022\031\n\025invalid_subscriber_id\020\001\022\027\n\023invalid_" +
      "carrier_key\020\002*l\n\030coverage_object_validit" +
      "y\022\"\n\036coverage_object_validity_valid\020\000\022,\n" +
      "(coverage_object_validity_invalid_pub_ke" +
      "y\020\001*\230\004\n\022heartbeat_validity\022\034\n\030heartbeat_" +
      "validity_valid\020\000\0222\n*heartbeat_validity_g" +
      "ateway_owner_not_found\020\001\032\002\010\001\022.\n*heartbea" +
      "t_validity_heartbeat_outside_range\020\002\022\"\n\036" +
      "heartbeat_validity_bad_cbsd_id\020\003\022&\n\"hear" +
      "tbeat_validity_not_operational\020\004\022(\n$hear" +
      "tbeat_validity_gateway_not_found\020\005\022.\n*he" +
      "artbeat_validity_no_such_coverage_object" +
      "\020\006\022*\n&heartbeat_validity_bad_coverage_ob" +
      "ject\020\007\022&\n\"heartbeat_validity_invalid_lat" +
      "_lon\020\010\022,\n(heartbeat_validity_too_far_fro" +
      "m_coverage\020\t\022+\n\'heartbeat_validity_gatew" +
      "ay_not_asserted\020\n\022+\n\'heartbeat_validity_" +
      "unsupported_location\020\013*~\n\027seniority_upda" +
      "te_reason\022.\n*seniority_update_reason_hea" +
      "rtbeat_not_seen\020\000\0223\n/seniority_update_re" +
      "ason_new_coverage_claim_time\020\001*\202\002\n\027unall" +
      "ocated_reward_type\022\037\n\033unallocated_reward" +
      "_type_poc\020\000\022.\n*unallocated_reward_type_d" +
      "iscovery_location\020\001\022\"\n\036unallocated_rewar" +
      "d_type_mapper\020\002\022,\n(unallocated_reward_ty" +
      "pe_service_provider\020\003\022\"\n\036unallocated_rew" +
      "ard_type_oracle\020\004\022 \n\034unallocated_reward_" +
      "type_data\020\005*\355\001\n\026speedtest_avg_validity\022 " +
      "\n\034speedtest_avg_validity_valid\020\000\022*\n&spee" +
      "dtest_avg_validity_too_few_samples\020\001\022.\n*" +
      "speedtest_avg_validity_slow_download_spe" +
      "ed\020\002\022,\n(speedtest_avg_validity_slow_uplo" +
      "ad_speed\020\003\022\'\n#speedtest_avg_validity_hig" +
      "h_latency\020\004*=\n\tfile_type\022\027\n\023file_type_he" +
      "artbeat\020\000\022\027\n\023file_type_speedtest\020\001*\262\001\n\tc" +
      "ell_type\022\014\n\010nova436h\020\000\022\014\n\010nova430i\020\001\022\017\n\013" +
      "neutrino430\020\002\022\022\n\016sercomm_indoor\020\003\022\023\n\017ser" +
      "comm_outdoor\020\004\022\022\n\016cell_type_none\020\005\022\034\n\030no" +
      "va_generic_wifi_indoor\020\006\022\035\n\031nova_generic" +
      "_wifi_outdoor\020\007*p\n%data_transfer_radio_a" +
      "ccess_technology\022\t\n\005UTRAN\020\000\022\t\n\005GERAN\020\001\022\010" +
      "\n\004WLAN\020\002\022\007\n\003GAN\020\003\022\022\n\016HSPA_Evolution\020\004\022\n\n" +
      "\006EUTRAN\020\0052\336\007\n\npoc_mobile\022]\n\020submit_speed" +
      "test\022#.helium.poc_mobile.speedtest_req_v" +
      "1\032$.helium.poc_mobile.speedtest_resp_v1\022" +
      "l\n\025submit_cell_heartbeat\022(.helium.poc_mo" +
      "bile.cell_heartbeat_req_v1\032).helium.poc_" +
      "mobile.cell_heartbeat_resp_v1\022l\n\025submit_" +
      "wifi_heartbeat\022(.helium.poc_mobile.wifi_" +
      "heartbeat_req_v1\032).helium.poc_mobile.wif" +
      "i_heartbeat_resp_v1\022\201\001\n\034submit_data_tran" +
      "sfer_session\022/.helium.poc_mobile.data_tr" +
      "ansfer_session_req_v1\0320.helium.poc_mobil" +
      "e.data_transfer_session_resp_v1\022{\n\032submi" +
      "t_subscriber_location\022-.helium.poc_mobil" +
      "e.subscriber_location_req_v1\032..helium.po" +
      "c_mobile.subscriber_location_resp_v1\022o\n\026" +
      "submit_coverage_object\022).helium.poc_mobi" +
      "le.coverage_object_req_v1\032*.helium.poc_m" +
      "obile.coverage_object_resp_v1\022~\n\027submit_" +
      "threshold_report\0220.helium.poc_mobile.rad" +
      "io_threshold_report_req_v1\0321.helium.poc_" +
      "mobile.radio_threshold_report_resp_v1\022\242\001" +
      "\n#submit_invalidated_threshold_report\022<." +
      "helium.poc_mobile.invalidated_radio_thre" +
      "shold_report_req_v1\032=.helium.poc_mobile." +
      "invalidated_radio_threshold_report_resp_" +
      "v1B%\n\026com.helium.grpc.mobileB\tPocMobileP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MapperClass.getDescriptor(),
          HexBoosting.getDescriptor(),
          ServiceProvider.getDescriptor(),
        });
    internal_static_helium_poc_mobile_speedtest_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helium_poc_mobile_speedtest_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_speedtest_req_v1_descriptor,
        new java.lang.String[] { "PubKey", "Serial", "Timestamp", "UploadSpeed", "DownloadSpeed", "Latency", "Signature", });
    internal_static_helium_poc_mobile_speedtest_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helium_poc_mobile_speedtest_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_speedtest_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_speedtest_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helium_poc_mobile_speedtest_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_speedtest_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_verified_speedtest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helium_poc_mobile_verified_speedtest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_verified_speedtest_descriptor,
        new java.lang.String[] { "Report", "Result", "Timestamp", });
    internal_static_helium_poc_mobile_cell_heartbeat_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helium_poc_mobile_cell_heartbeat_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_cell_heartbeat_req_v1_descriptor,
        new java.lang.String[] { "PubKey", "HotspotType", "CellId", "Timestamp", "Lat", "Lon", "OperationMode", "CbsdCategory", "CbsdId", "Signature", "CoverageObject", });
    internal_static_helium_poc_mobile_cell_heartbeat_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helium_poc_mobile_cell_heartbeat_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_cell_heartbeat_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_cell_heartbeat_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helium_poc_mobile_cell_heartbeat_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_cell_heartbeat_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_wifi_heartbeat_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_helium_poc_mobile_wifi_heartbeat_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_wifi_heartbeat_req_v1_descriptor,
        new java.lang.String[] { "PubKey", "Timestamp", "Lat", "Lon", "LocationValidationTimestamp", "OperationMode", "CoverageObject", "Signature", });
    internal_static_helium_poc_mobile_wifi_heartbeat_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_helium_poc_mobile_wifi_heartbeat_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_wifi_heartbeat_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_wifi_heartbeat_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_helium_poc_mobile_wifi_heartbeat_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_wifi_heartbeat_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_mapper_attach_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_helium_poc_mobile_mapper_attach_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_mapper_attach_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_subscriber_location_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_helium_poc_mobile_subscriber_location_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_subscriber_location_req_v1_descriptor,
        new java.lang.String[] { "SubscriberId", "Timestamp", "CarrierPubKey", "Signature", });
    internal_static_helium_poc_mobile_subscriber_location_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_helium_poc_mobile_subscriber_location_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_subscriber_location_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_subscriber_location_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_helium_poc_mobile_subscriber_location_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_subscriber_location_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_radio_threshold_report_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_helium_poc_mobile_radio_threshold_report_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_threshold_report_req_v1_descriptor,
        new java.lang.String[] { "CbsdId", "HotspotPubkey", "BytesThreshold", "SubscriberThreshold", "ThresholdTimestamp", "CarrierPubKey", "Signature", });
    internal_static_helium_poc_mobile_radio_threshold_report_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_helium_poc_mobile_radio_threshold_report_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_threshold_report_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_radio_threshold_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_helium_poc_mobile_radio_threshold_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_threshold_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_verified_radio_threshold_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_helium_poc_mobile_verified_radio_threshold_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_verified_radio_threshold_ingest_report_v1_descriptor,
        new java.lang.String[] { "Report", "Status", "Timestamp", });
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_invalidated_radio_threshold_report_req_v1_descriptor,
        new java.lang.String[] { "CbsdId", "HotspotPubkey", "Reason", "Timestamp", "CarrierPubKey", "Signature", });
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_helium_poc_mobile_invalidated_radio_threshold_report_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_invalidated_radio_threshold_report_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_invalidated_radio_threshold_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_helium_poc_mobile_invalidated_radio_threshold_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_invalidated_radio_threshold_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_verified_invalidated_radio_threshold_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_helium_poc_mobile_verified_invalidated_radio_threshold_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_verified_invalidated_radio_threshold_ingest_report_v1_descriptor,
        new java.lang.String[] { "Report", "Status", "Timestamp", });
    internal_static_helium_poc_mobile_radio_hex_signal_level_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_helium_poc_mobile_radio_hex_signal_level_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_hex_signal_level_descriptor,
        new java.lang.String[] { "Location", "SignalLevel", "SignalPower", });
    internal_static_helium_poc_mobile_coverage_object_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_helium_poc_mobile_coverage_object_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_coverage_object_req_v1_descriptor,
        new java.lang.String[] { "PubKey", "Uuid", "CbsdId", "HotspotKey", "CoverageClaimTime", "Coverage", "Indoor", "TrustScore", "Signature", "KeyType", });
    internal_static_helium_poc_mobile_coverage_object_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_helium_poc_mobile_coverage_object_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_coverage_object_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_coverage_object_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_helium_poc_mobile_coverage_object_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_coverage_object_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_verified_subscriber_location_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_helium_poc_mobile_verified_subscriber_location_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_verified_subscriber_location_ingest_report_v1_descriptor,
        new java.lang.String[] { "Report", "Status", "Timestamp", });
    internal_static_helium_poc_mobile_file_info_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_helium_poc_mobile_file_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_file_info_descriptor,
        new java.lang.String[] { "Key", "FileType", "Timestamp", "Size", });
    internal_static_helium_poc_mobile_processed_files_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_helium_poc_mobile_processed_files_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_processed_files_descriptor,
        new java.lang.String[] { "Files", });
    internal_static_helium_poc_mobile_coverage_object_v1_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_helium_poc_mobile_coverage_object_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_coverage_object_v1_descriptor,
        new java.lang.String[] { "CoverageObject", "Validity", });
    internal_static_helium_poc_mobile_heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_helium_poc_mobile_heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_heartbeat_descriptor,
        new java.lang.String[] { "CbsdId", "PubKey", "RewardMultiplier", "Timestamp", "CellType", "Validity", "Lat", "Lon", "CoverageObject", "LocationValidationTimestamp", "DistanceToAsserted", "LocationTrustScoreMultiplier", });
    internal_static_helium_poc_mobile_seniority_update_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_helium_poc_mobile_seniority_update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_seniority_update_descriptor,
        new java.lang.String[] { "CbsdId", "HotspotKey", "NewSeniorityTimestamp", "Reason", "KeyType", });
    internal_static_helium_poc_mobile_speedtest_avg_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_helium_poc_mobile_speedtest_avg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_speedtest_avg_descriptor,
        new java.lang.String[] { "PubKey", "UploadSpeedAvgBps", "DownloadSpeedAvgBps", "LatencyAvgMs", "Validity", "Speedtests", "Timestamp", "RewardMultiplier", });
    internal_static_helium_poc_mobile_speedtest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_helium_poc_mobile_speedtest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_speedtest_descriptor,
        new java.lang.String[] { "UploadSpeedBps", "DownloadSpeedBps", "LatencyMs", "Timestamp", });
    internal_static_helium_poc_mobile_radio_reward_share_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_helium_poc_mobile_radio_reward_share_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_reward_share_descriptor,
        new java.lang.String[] { "OwnerKey", "HotspotKey", "CbsdId", "Amount", "StartEpoch", "EndEpoch", });
    internal_static_helium_poc_mobile_radio_reward_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_helium_poc_mobile_radio_reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_radio_reward_descriptor,
        new java.lang.String[] { "HotspotKey", "CbsdId", "DcTransferReward", "PocReward", "CoveragePoints", "SeniorityTimestamp", "CoverageObject", "LocationTrustScoreMultiplier", "SpeedtestMultiplier", "BoostedHexes", });
    internal_static_helium_poc_mobile_boosted_hex_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_helium_poc_mobile_boosted_hex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_boosted_hex_descriptor,
        new java.lang.String[] { "Location", "Multiplier", });
    internal_static_helium_poc_mobile_gateway_reward_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_helium_poc_mobile_gateway_reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_gateway_reward_descriptor,
        new java.lang.String[] { "HotspotKey", "DcTransferReward", "RewardableBytes", "Price", });
    internal_static_helium_poc_mobile_subscriber_reward_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_helium_poc_mobile_subscriber_reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_subscriber_reward_descriptor,
        new java.lang.String[] { "SubscriberId", "DiscoveryLocationAmount", });
    internal_static_helium_poc_mobile_service_provider_reward_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_helium_poc_mobile_service_provider_reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_service_provider_reward_descriptor,
        new java.lang.String[] { "ServiceProviderId", "Amount", });
    internal_static_helium_poc_mobile_unallocated_reward_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_helium_poc_mobile_unallocated_reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_unallocated_reward_descriptor,
        new java.lang.String[] { "RewardType", "Amount", });
    internal_static_helium_poc_mobile_mobile_reward_share_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_helium_poc_mobile_mobile_reward_share_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_mobile_reward_share_descriptor,
        new java.lang.String[] { "StartPeriod", "EndPeriod", "RadioReward", "GatewayReward", "SubscriberReward", "ServiceProviderReward", "UnallocatedReward", "Reward", });
    internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_helium_poc_mobile_data_transfer_session_req_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_data_transfer_session_req_v1_descriptor,
        new java.lang.String[] { "DataTransferUsage", "RewardCancelled", "PubKey", "Signature", "RewardableBytes", });
    internal_static_helium_poc_mobile_data_transfer_event_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_helium_poc_mobile_data_transfer_event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_data_transfer_event_descriptor,
        new java.lang.String[] { "PubKey", "UploadBytes", "DownloadBytes", "RadioAccessTechnology", "EventId", "Payer", "Timestamp", "Signature", });
    internal_static_helium_poc_mobile_data_transfer_session_resp_v1_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_helium_poc_mobile_data_transfer_session_resp_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_data_transfer_session_resp_v1_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_helium_poc_mobile_data_transfer_session_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_helium_poc_mobile_data_transfer_session_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_data_transfer_session_ingest_report_v1_descriptor,
        new java.lang.String[] { "ReceivedTimestamp", "Report", });
    internal_static_helium_poc_mobile_invalid_data_transfer_ingest_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_helium_poc_mobile_invalid_data_transfer_ingest_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_invalid_data_transfer_ingest_report_v1_descriptor,
        new java.lang.String[] { "Report", "Reason", "Timestamp", });
    internal_static_helium_poc_mobile_oracle_boosting_report_v1_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_helium_poc_mobile_oracle_boosting_report_v1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_oracle_boosting_report_v1_descriptor,
        new java.lang.String[] { "CoverageObject", "Assignments", "Timestamp", });
    internal_static_helium_poc_mobile_oracle_boosting_hex_assignment_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_helium_poc_mobile_oracle_boosting_hex_assignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helium_poc_mobile_oracle_boosting_hex_assignment_descriptor,
        new java.lang.String[] { "Location", "AssignmentMultiplier", "Urbanized", });
    MapperClass.getDescriptor();
    HexBoosting.getDescriptor();
    ServiceProvider.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
