// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface radio_threshold_report_req_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.radio_threshold_report_req_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id of the radio which has met the coverage threshold requirements
   * CBRS radios only
   * </pre>
   *
   * <code>string cbsd_id = 1;</code>
   * @return The cbsdId.
   */
  java.lang.String getCbsdId();
  /**
   * <pre>
   * the id of the radio which has met the coverage threshold requirements
   * CBRS radios only
   * </pre>
   *
   * <code>string cbsd_id = 1;</code>
   * @return The bytes for cbsdId.
   */
  com.google.protobuf.ByteString
      getCbsdIdBytes();

  /**
   * <pre>
   * The onchain address of the gateway which has met the coverage
   * threshold requirements
   * </pre>
   *
   * <code>bytes hotspot_pubkey = 2;</code>
   * @return The hotspotPubkey.
   */
  com.google.protobuf.ByteString getHotspotPubkey();

  /**
   * <pre>
   * the threshold value representing the amount of transferred bytes the
   * minimum number of subscribers as defined by subscriber_threshold have
   * exceeded
   * </pre>
   *
   * <code>uint64 bytes_threshold = 3;</code>
   * @return The bytesThreshold.
   */
  long getBytesThreshold();

  /**
   * <pre>
   * the threshold value representing the minimum number of subscribers
   * that have exceeded the bytes_threshold for the hotspot
   * </pre>
   *
   * <code>uint32 subscriber_threshold = 4;</code>
   * @return The subscriberThreshold.
   */
  int getSubscriberThreshold();

  /**
   * <pre>
   * Unix timestamp in seconds when the thresholds were exceeded
   * </pre>
   *
   * <code>uint64 threshold_timestamp = 5;</code>
   * @return The thresholdTimestamp.
   */
  long getThresholdTimestamp();

  /**
   * <pre>
   * pubkey of the carrier identity service
   * </pre>
   *
   * <code>bytes carrier_pub_key = 6;</code>
   * @return The carrierPubKey.
   */
  com.google.protobuf.ByteString getCarrierPubKey();

  /**
   * <pre>
   * signed payload of the carrier identity service
   * </pre>
   *
   * <code>bytes signature = 7;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
