// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_mobile.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc.mobile;

@java.lang.Deprecated public interface radio_reward_shareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.radio_reward_share)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; Public key of the owner of the radio
   * </pre>
   *
   * <code>bytes owner_key = 1;</code>
   * @return The ownerKey.
   */
  com.google.protobuf.ByteString getOwnerKey();

  /**
   * <pre>
   *&#47; Public key of the hotspot of the radio
   * </pre>
   *
   * <code>bytes hotspot_key = 2;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <pre>
   *&#47; cbsd Id of the radio
   * </pre>
   *
   * <code>string cbsd_id = 3;</code>
   * @return The cbsdId.
   */
  java.lang.String getCbsdId();
  /**
   * <pre>
   *&#47; cbsd Id of the radio
   * </pre>
   *
   * <code>string cbsd_id = 3;</code>
   * @return The bytes for cbsdId.
   */
  com.google.protobuf.ByteString
      getCbsdIdBytes();

  /**
   * <pre>
   *&#47; Amount rewarded to the owner of the radio
   * </pre>
   *
   * <code>uint64 amount = 4;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <pre>
   *&#47; Unix timestamp in seconds of the start of the reward period
   * </pre>
   *
   * <code>uint64 start_epoch = 5;</code>
   * @return The startEpoch.
   */
  long getStartEpoch();

  /**
   * <pre>
   *&#47; Unix timestamp in seconds of the end of the reward period
   * </pre>
   *
   * <code>uint64 end_epoch = 6;</code>
   * @return The endEpoch.
   */
  long getEndEpoch();
}
