// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface seniority_updateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.seniority_update)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 1;</code>
   * @return Whether the cbsdId field is set.
   */
  boolean hasCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 1;</code>
   * @return The cbsdId.
   */
  java.lang.String getCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 1;</code>
   * @return The bytes for cbsdId.
   */
  com.google.protobuf.ByteString
      getCbsdIdBytes();

  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 2;</code>
   * @return Whether the hotspotKey field is set.
   */
  boolean hasHotspotKey();
  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 2;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <pre>
   * Timestamp of the new seniority for the radio
   * </pre>
   *
   * <code>uint64 new_seniority_timestamp = 3 [deprecated = true];</code>
   * @deprecated helium.poc_mobile.seniority_update.new_seniority_timestamp is deprecated.
   *     See service/poc_mobile.proto;l=515
   * @return The newSeniorityTimestamp.
   */
  @java.lang.Deprecated long getNewSeniorityTimestamp();

  /**
   * <code>.helium.poc_mobile.seniority_update_reason reason = 4;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.helium.poc_mobile.seniority_update_reason reason = 4;</code>
   * @return The reason.
   */
  com.helium.grpc.mobile.seniority_update_reason getReason();

  /**
   * <pre>
   * Timestamp in milliseconds of the new seniority for the radio
   * </pre>
   *
   * <code>uint64 new_seniority_timestamp_ms = 5;</code>
   * @return The newSeniorityTimestampMs.
   */
  long getNewSeniorityTimestampMs();

  com.helium.grpc.mobile.seniority_update.KeyTypeCase getKeyTypeCase();
}
