// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_provider.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc.mobile;

public final class ServiceProvider {
  private ServiceProvider() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026service_provider.proto\022\006helium*%\n\020serv" +
      "ice_provider\022\021\n\rhelium_mobile\020\000B+\n\026com.h" +
      "elium.grpc.mobileB\017ServiceProviderP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
