// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface service_provider_boosted_rewards_banned_radio_req_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.service_provider_boosted_rewards_banned_radio_req_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * pubkey of signer
   * </pre>
   *
   * <code>bytes pubkey = 1;</code>
   * @return The pubkey.
   */
  com.google.protobuf.ByteString getPubkey();

  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 2;</code>
   * @return Whether the cbsdId field is set.
   */
  boolean hasCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 2;</code>
   * @return The cbsdId.
   */
  java.lang.String getCbsdId();
  /**
   * <pre>
   * For CBRS radio
   * </pre>
   *
   * <code>string cbsd_id = 2;</code>
   * @return The bytes for cbsdId.
   */
  com.google.protobuf.ByteString
      getCbsdIdBytes();

  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 3;</code>
   * @return Whether the hotspotKey field is set.
   */
  boolean hasHotspotKey();
  /**
   * <pre>
   * For WiFi radio
   * </pre>
   *
   * <code>bytes hotspot_key = 3;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <code>.helium.poc_mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_reason reason = 4;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.helium.poc_mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_reason reason = 4;</code>
   * @return The reason.
   */
  com.helium.grpc.mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_reason getReason();

  /**
   * <pre>
   * Timestamp in seconds since epoch of when ban ends
   * </pre>
   *
   * <code>uint64 until = 5;</code>
   * @return The until.
   */
  long getUntil();

  /**
   * <code>bytes signature = 6;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>.helium.poc_mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_ban_type ban_type = 7;</code>
   * @return The enum numeric value on the wire for banType.
   */
  int getBanTypeValue();
  /**
   * <code>.helium.poc_mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_ban_type ban_type = 7;</code>
   * @return The banType.
   */
  com.helium.grpc.mobile.service_provider_boosted_rewards_banned_radio_req_v1.sp_boosted_rewards_banned_radio_ban_type getBanType();

  com.helium.grpc.mobile.service_provider_boosted_rewards_banned_radio_req_v1.KeyTypeCase getKeyTypeCase();
}
