// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_mobile.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc.mobile;

public interface service_provider_rewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.service_provider_reward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * rewardable entity id of the service provider to which the reward will be
   * credited
   * </pre>
   *
   * <code>.helium.service_provider service_provider_id = 1;</code>
   * @return The enum numeric value on the wire for serviceProviderId.
   */
  int getServiceProviderIdValue();
  /**
   * <pre>
   * rewardable entity id of the service provider to which the reward will be
   * credited
   * </pre>
   *
   * <code>.helium.service_provider service_provider_id = 1;</code>
   * @return The serviceProviderId.
   */
  service_provider getServiceProviderId();

  /**
   * <pre>
   *&#47; Amount in bones rewarded
   * </pre>
   *
   * <code>uint64 amount = 2;</code>
   * @return The amount.
   */
  long getAmount();
}
