// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface speedtestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.speedtest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 upload_speed_bps = 1;</code>
   * @return The uploadSpeedBps.
   */
  long getUploadSpeedBps();

  /**
   * <code>uint64 download_speed_bps = 2;</code>
   * @return The downloadSpeedBps.
   */
  long getDownloadSpeedBps();

  /**
   * <code>uint32 latency_ms = 3;</code>
   * @return The latencyMs.
   */
  int getLatencyMs();

  /**
   * <code>uint64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
