// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

/**
 * Protobuf type {@code helium.poc_mobile.speedtest_req_v1}
 */
public final class speedtest_req_v1 extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helium.poc_mobile.speedtest_req_v1)
    speedtest_req_v1OrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      speedtest_req_v1.class.getName());
  }
  // Use speedtest_req_v1.newBuilder() to construct.
  private speedtest_req_v1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private speedtest_req_v1() {
    pubKey_ = com.google.protobuf.ByteString.EMPTY;
    serial_ = "";
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_speedtest_req_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_speedtest_req_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.mobile.speedtest_req_v1.class, com.helium.grpc.mobile.speedtest_req_v1.Builder.class);
  }

  public static final int PUB_KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes pub_key = 1;</code>
   * @return The pubKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPubKey() {
    return pubKey_;
  }

  public static final int SERIAL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serial_ = "";
  /**
   * <code>string serial = 2;</code>
   * @return The serial.
   */
  @java.lang.Override
  public java.lang.String getSerial() {
    java.lang.Object ref = serial_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serial_ = s;
      return s;
    }
  }
  /**
   * <code>string serial = 2;</code>
   * @return The bytes for serial.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSerialBytes() {
    java.lang.Object ref = serial_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serial_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * &#47; Timestamp of speedtest test in seconds from unix epoch
   * </pre>
   *
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int UPLOAD_SPEED_FIELD_NUMBER = 4;
  private long uploadSpeed_ = 0L;
  /**
   * <pre>
   * &#47; Measured upload speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
   * </pre>
   *
   * <code>uint64 upload_speed = 4;</code>
   * @return The uploadSpeed.
   */
  @java.lang.Override
  public long getUploadSpeed() {
    return uploadSpeed_;
  }

  public static final int DOWNLOAD_SPEED_FIELD_NUMBER = 5;
  private long downloadSpeed_ = 0L;
  /**
   * <pre>
   * &#47; Measured download speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
   * </pre>
   *
   * <code>uint64 download_speed = 5;</code>
   * @return The downloadSpeed.
   */
  @java.lang.Override
  public long getDownloadSpeed() {
    return downloadSpeed_;
  }

  public static final int LATENCY_FIELD_NUMBER = 6;
  private int latency_ = 0;
  /**
   * <pre>
   * &#47; Measured latency in milliseconds
   * </pre>
   *
   * <code>uint32 latency = 6;</code>
   * @return The latency.
   */
  @java.lang.Override
  public int getLatency() {
    return latency_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes signature = 7;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!pubKey_.isEmpty()) {
      output.writeBytes(1, pubKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serial_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, serial_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(3, timestamp_);
    }
    if (uploadSpeed_ != 0L) {
      output.writeUInt64(4, uploadSpeed_);
    }
    if (downloadSpeed_ != 0L) {
      output.writeUInt64(5, downloadSpeed_);
    }
    if (latency_ != 0) {
      output.writeUInt32(6, latency_);
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(7, signature_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!pubKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, pubKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serial_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, serial_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    if (uploadSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, uploadSpeed_);
    }
    if (downloadSpeed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, downloadSpeed_);
    }
    if (latency_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, latency_);
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, signature_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.mobile.speedtest_req_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.mobile.speedtest_req_v1 other = (com.helium.grpc.mobile.speedtest_req_v1) obj;

    if (!getPubKey()
        .equals(other.getPubKey())) return false;
    if (!getSerial()
        .equals(other.getSerial())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getUploadSpeed()
        != other.getUploadSpeed()) return false;
    if (getDownloadSpeed()
        != other.getDownloadSpeed()) return false;
    if (getLatency()
        != other.getLatency()) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PUB_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getPubKey().hashCode();
    hash = (37 * hash) + SERIAL_FIELD_NUMBER;
    hash = (53 * hash) + getSerial().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + UPLOAD_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUploadSpeed());
    hash = (37 * hash) + DOWNLOAD_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDownloadSpeed());
    hash = (37 * hash) + LATENCY_FIELD_NUMBER;
    hash = (53 * hash) + getLatency();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.helium.grpc.mobile.speedtest_req_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.helium.grpc.mobile.speedtest_req_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.mobile.speedtest_req_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.mobile.speedtest_req_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.poc_mobile.speedtest_req_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.poc_mobile.speedtest_req_v1)
      com.helium.grpc.mobile.speedtest_req_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_speedtest_req_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_speedtest_req_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.mobile.speedtest_req_v1.class, com.helium.grpc.mobile.speedtest_req_v1.Builder.class);
    }

    // Construct using com.helium.grpc.mobile.speedtest_req_v1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
      serial_ = "";
      timestamp_ = 0L;
      uploadSpeed_ = 0L;
      downloadSpeed_ = 0L;
      latency_ = 0;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.mobile.PocMobile.internal_static_helium_poc_mobile_speedtest_req_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.mobile.speedtest_req_v1 getDefaultInstanceForType() {
      return com.helium.grpc.mobile.speedtest_req_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.mobile.speedtest_req_v1 build() {
      com.helium.grpc.mobile.speedtest_req_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.mobile.speedtest_req_v1 buildPartial() {
      com.helium.grpc.mobile.speedtest_req_v1 result = new com.helium.grpc.mobile.speedtest_req_v1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.helium.grpc.mobile.speedtest_req_v1 result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pubKey_ = pubKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serial_ = serial_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.uploadSpeed_ = uploadSpeed_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.downloadSpeed_ = downloadSpeed_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.latency_ = latency_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.signature_ = signature_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.mobile.speedtest_req_v1) {
        return mergeFrom((com.helium.grpc.mobile.speedtest_req_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.mobile.speedtest_req_v1 other) {
      if (other == com.helium.grpc.mobile.speedtest_req_v1.getDefaultInstance()) return this;
      if (other.getPubKey() != com.google.protobuf.ByteString.EMPTY) {
        setPubKey(other.getPubKey());
      }
      if (!other.getSerial().isEmpty()) {
        serial_ = other.serial_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getUploadSpeed() != 0L) {
        setUploadSpeed(other.getUploadSpeed());
      }
      if (other.getDownloadSpeed() != 0L) {
        setDownloadSpeed(other.getDownloadSpeed());
      }
      if (other.getLatency() != 0) {
        setLatency(other.getLatency());
      }
      if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
        setSignature(other.getSignature());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pubKey_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              serial_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              timestamp_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              uploadSpeed_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              downloadSpeed_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              latency_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pub_key = 1;</code>
     * @return The pubKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }
    /**
     * <code>bytes pub_key = 1;</code>
     * @param value The pubKey to set.
     * @return This builder for chaining.
     */
    public Builder setPubKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      pubKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pub_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPubKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pubKey_ = getDefaultInstance().getPubKey();
      onChanged();
      return this;
    }

    private java.lang.Object serial_ = "";
    /**
     * <code>string serial = 2;</code>
     * @return The serial.
     */
    public java.lang.String getSerial() {
      java.lang.Object ref = serial_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serial_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serial = 2;</code>
     * @return The bytes for serial.
     */
    public com.google.protobuf.ByteString
        getSerialBytes() {
      java.lang.Object ref = serial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serial = 2;</code>
     * @param value The serial to set.
     * @return This builder for chaining.
     */
    public Builder setSerial(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serial_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string serial = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerial() {
      serial_ = getDefaultInstance().getSerial();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string serial = 2;</code>
     * @param value The bytes for serial to set.
     * @return This builder for chaining.
     */
    public Builder setSerialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serial_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * &#47; Timestamp of speedtest test in seconds from unix epoch
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * &#47; Timestamp of speedtest test in seconds from unix epoch
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; Timestamp of speedtest test in seconds from unix epoch
     * </pre>
     *
     * <code>uint64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long uploadSpeed_ ;
    /**
     * <pre>
     * &#47; Measured upload speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 upload_speed = 4;</code>
     * @return The uploadSpeed.
     */
    @java.lang.Override
    public long getUploadSpeed() {
      return uploadSpeed_;
    }
    /**
     * <pre>
     * &#47; Measured upload speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 upload_speed = 4;</code>
     * @param value The uploadSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setUploadSpeed(long value) {

      uploadSpeed_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; Measured upload speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 upload_speed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUploadSpeed() {
      bitField0_ = (bitField0_ & ~0x00000008);
      uploadSpeed_ = 0L;
      onChanged();
      return this;
    }

    private long downloadSpeed_ ;
    /**
     * <pre>
     * &#47; Measured download speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 download_speed = 5;</code>
     * @return The downloadSpeed.
     */
    @java.lang.Override
    public long getDownloadSpeed() {
      return downloadSpeed_;
    }
    /**
     * <pre>
     * &#47; Measured download speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 download_speed = 5;</code>
     * @param value The downloadSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setDownloadSpeed(long value) {

      downloadSpeed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; Measured download speed in bytes/sec. &lt;value&gt;*8/10E5 = Mbps
     * </pre>
     *
     * <code>uint64 download_speed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloadSpeed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      downloadSpeed_ = 0L;
      onChanged();
      return this;
    }

    private int latency_ ;
    /**
     * <pre>
     * &#47; Measured latency in milliseconds
     * </pre>
     *
     * <code>uint32 latency = 6;</code>
     * @return The latency.
     */
    @java.lang.Override
    public int getLatency() {
      return latency_;
    }
    /**
     * <pre>
     * &#47; Measured latency in milliseconds
     * </pre>
     *
     * <code>uint32 latency = 6;</code>
     * @param value The latency to set.
     * @return This builder for chaining.
     */
    public Builder setLatency(int value) {

      latency_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; Measured latency in milliseconds
     * </pre>
     *
     * <code>uint32 latency = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatency() {
      bitField0_ = (bitField0_ & ~0x00000020);
      latency_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature = 7;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>bytes signature = 7;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000040);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helium.poc_mobile.speedtest_req_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.poc_mobile.speedtest_req_v1)
  private static final com.helium.grpc.mobile.speedtest_req_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.mobile.speedtest_req_v1();
  }

  public static com.helium.grpc.mobile.speedtest_req_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<speedtest_req_v1>
      PARSER = new com.google.protobuf.AbstractParser<speedtest_req_v1>() {
    @java.lang.Override
    public speedtest_req_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<speedtest_req_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<speedtest_req_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.mobile.speedtest_req_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

