// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

/**
 * Protobuf enum {@code helium.poc_mobile.speedtest_avg_validity}
 */
public enum speedtest_avg_validity
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>speedtest_avg_validity_valid = 0;</code>
   */
  speedtest_avg_validity_valid(0),
  /**
   * <code>speedtest_avg_validity_too_few_samples = 1;</code>
   */
  speedtest_avg_validity_too_few_samples(1),
  /**
   * <code>speedtest_avg_validity_slow_download_speed = 2;</code>
   */
  speedtest_avg_validity_slow_download_speed(2),
  /**
   * <code>speedtest_avg_validity_slow_upload_speed = 3;</code>
   */
  speedtest_avg_validity_slow_upload_speed(3),
  /**
   * <code>speedtest_avg_validity_high_latency = 4;</code>
   */
  speedtest_avg_validity_high_latency(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      speedtest_avg_validity.class.getName());
  }
  /**
   * <code>speedtest_avg_validity_valid = 0;</code>
   */
  public static final int speedtest_avg_validity_valid_VALUE = 0;
  /**
   * <code>speedtest_avg_validity_too_few_samples = 1;</code>
   */
  public static final int speedtest_avg_validity_too_few_samples_VALUE = 1;
  /**
   * <code>speedtest_avg_validity_slow_download_speed = 2;</code>
   */
  public static final int speedtest_avg_validity_slow_download_speed_VALUE = 2;
  /**
   * <code>speedtest_avg_validity_slow_upload_speed = 3;</code>
   */
  public static final int speedtest_avg_validity_slow_upload_speed_VALUE = 3;
  /**
   * <code>speedtest_avg_validity_high_latency = 4;</code>
   */
  public static final int speedtest_avg_validity_high_latency_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static speedtest_avg_validity valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static speedtest_avg_validity forNumber(int value) {
    switch (value) {
      case 0: return speedtest_avg_validity_valid;
      case 1: return speedtest_avg_validity_too_few_samples;
      case 2: return speedtest_avg_validity_slow_download_speed;
      case 3: return speedtest_avg_validity_slow_upload_speed;
      case 4: return speedtest_avg_validity_high_latency;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<speedtest_avg_validity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      speedtest_avg_validity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<speedtest_avg_validity>() {
          public speedtest_avg_validity findValueByNumber(int number) {
            return speedtest_avg_validity.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.helium.grpc.mobile.PocMobile.getDescriptor().getEnumTypes().get(14);
  }

  private static final speedtest_avg_validity[] VALUES = values();

  public static speedtest_avg_validity valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private speedtest_avg_validity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:helium.poc_mobile.speedtest_avg_validity)
}

