// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface subscriber_location_req_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.subscriber_location_req_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * id of the subscriber which submitted the location report
   * </pre>
   *
   * <code>bytes subscriber_id = 1;</code>
   * @return The subscriberId.
   */
  com.google.protobuf.ByteString getSubscriberId();

  /**
   * <pre>
   * Timestamp of the subscriber location sharing event in seconds from the unix
   * epoch
   * </pre>
   *
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * pubkey of the carrier identity service
   * </pre>
   *
   * <code>bytes carrier_pub_key = 3;</code>
   * @return The carrierPubKey.
   */
  com.google.protobuf.ByteString getCarrierPubKey();

  /**
   * <pre>
   * signed payload of the carrier identity service
   * </pre>
   *
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
