// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_mobile.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc.mobile;

public interface verified_subscriber_verified_mapping_event_ingest_report_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_mobile.verified_subscriber_verified_mapping_event_ingest_report_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the verified report
   * </pre>
   *
   * <code>.helium.poc_mobile.subscriber_verified_mapping_event_ingest_report_v1 report = 1;</code>
   * @return Whether the report field is set.
   */
  boolean hasReport();
  /**
   * <pre>
   * the verified report
   * </pre>
   *
   * <code>.helium.poc_mobile.subscriber_verified_mapping_event_ingest_report_v1 report = 1;</code>
   * @return The report.
   */
  com.helium.grpc.mobile.subscriber_verified_mapping_event_ingest_report_v1 getReport();
  /**
   * <pre>
   * the verified report
   * </pre>
   *
   * <code>.helium.poc_mobile.subscriber_verified_mapping_event_ingest_report_v1 report = 1;</code>
   */
  com.helium.grpc.mobile.subscriber_verified_mapping_event_ingest_report_v1OrBuilder getReportOrBuilder();

  /**
   * <pre>
   * the status determined by the verification
   * </pre>
   *
   * <code>.helium.poc_mobile.subscriber_verified_mapping_event_verification_status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * the status determined by the verification
   * </pre>
   *
   * <code>.helium.poc_mobile.subscriber_verified_mapping_event_verification_status status = 2;</code>
   * @return The status.
   */
  com.helium.grpc.mobile.subscriber_verified_mapping_event_verification_status getStatus();

  /**
   * <pre>
   * Timestamp in milliseconds since unix epoch
   * </pre>
   *
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
