apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    basicAuth: false
    isDefault: true
    editable: true
    uid: PBFA97CFB590B2093