package fr.ingeniousthings.tools;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Animal {

    private static final Logger log = LoggerFactory.getLogger(Animal.class);

    /* ---
        const compress = (bytes, target) => {
          const { length } = bytes;
          if (target > length) throw new Error('Fewer input bytes than requested output');

          // Calculate the segment size (divide and round down)
          const segSize = length / target >> 0;

          // Split 'bytes' array into 'target' number of segments.
          [1,2,3,4,5,6,7,8,9,10]

          const segments = [];
          for (let i = 0; i < segSize * target; i += segSize) {
            segments.push(bytes.slice(i, i + segSize));
          }
            segment[] = [
                [ 1,2,3 ],
                [ 4,5,6 ],
                [ 7,8,9 ]
            ]


          // Catch any left-over bytes in the last segment.
          const lastSeg = segments[segments.length - 1];
          [ 7,8,9 ]
          segments[segments.length - 1] = lastSeg.concat(bytes.slice(target * segSize));
            segment[] = [
                [ 1,2,3 ],
                [ 4,5,6 ],
                [ 7,8,9,10 ]
            ]

          const checksums = segments.map(x => x.reduce((acc, curr) => acc ^ curr));
            checksums = [ 1^2^3, 4^5^6, 7^8^9^10 ]

          return checksums;
        };
     */

    protected static byte[] compress( byte[] bytes, int target ) {
        if ( bytes.length < target ) return null;
        int segSize = bytes.length / target;
        byte[] ret = new byte[target];
        int seg = 0, lsize = 0;
        for ( int i = 0; i < bytes.length ; i++ ) {
            if ( lsize == 0 ) ret[seg] = bytes[i];
            else ret[seg] ^= bytes[i];
            lsize++;
            if ( lsize == segSize && (bytes.length - i) >= segSize ) {
                seg++;
                lsize = 0;
            }
        }
        return ret;
    }

    /*
          const hexdigest = md5(input);
          const pairs = hexdigest.match(/(..?)/g);
          const bytes = pairs.map(x => parseInt(x, 16));
          const compressed = compress(bytes, 3);

          const adjective = adjectives[compressed[0]];
          const color = colors[compressed[1]];
          const animal = animals[compressed[2]];

          return format([adjective, color, animal], style, separator);
     */

    /**
     * As input, it gets the b58 string corresponding to the public key
     * @param publicKey
     * @param separator
     * @return
     */
    public static String getAnimalName(String publicKey, char separator) {
        return getAnimalName(publicKey.getBytes(),separator);
    }

    /**
     * As an input it get the b58 string
     * @param publicKey
     * @param separator
     * @return
     */
    public static String getAnimalName(byte[] publicKey, char separator) {
        String result ="";
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(publicKey);
            byte[] digest = md.digest();
            byte[] compressed = compress(digest,3);
            result = adjectives[(compressed[0]&0xFF)]+separator+
                     colors[(compressed[1]&0xFF)]+separator+
                     animals[(compressed[2]&0xFF)];
        } catch ( NoSuchAlgorithmException x ) {
             log.error("MD5 not supported "+x.getMessage());
        }
        return result;
    }


    protected static final String colors[] = {
            "white",
            "pearl",
            "alabaster",
            "snowy",
            "ivory",
            "cream",
            "cotton",
            "chiffon",
            "lace",
            "coconut",
            "linen",
            "bone",
            "daisy",
            "powder",
            "frost",
            "porcelain",
            "parchment",
            "velvet",
            "tan",
            "beige",
            "macaroon",
            "hazel",
            "felt",
            "metal",
            "gingham",
            "sand",
            "sepia",
            "latte",
            "vinyl",
            "glass",
            "hazelnut",
            "canvas",
            "wool",
            "yellow",
            "golden",
            "daffodil",
            "flaxen",
            "butter",
            "lemon",
            "mustard",
            "tartan",
            "blue",
            "cloth",
            "fiery",
            "banana",
            "plastic",
            "dijon",
            "honey",
            "blonde",
            "pineapple",
            "orange",
            "tangerine",
            "marigold",
            "cider",
            "rusty",
            "ginger",
            "tiger",
            "bronze",
            "fuzzy",
            "opaque",
            "clay",
            "carrot",
            "corduroy",
            "ceramic",
            "marmalade",
            "amber",
            "sandstone",
            "concrete",
            "red",
            "cherry",
            "hemp",
            "merlot",
            "garnet",
            "crimson",
            "ruby",
            "scarlet",
            "burlap",
            "brick",
            "bamboo",
            "mahogany",
            "blood",
            "sangria",
            "berry",
            "currant",
            "blush",
            "candy",
            "lipstick",
            "pink",
            "rose",
            "fuchsia",
            "punch",
            "watermelon",
            "rouge",
            "coral",
            "peach",
            "strawberry",
            "rosewood",
            "lemonade",
            "taffy",
            "bubblegum",
            "crepe",
            "hotpink",
            "purple",
            "mauve",
            "violet",
            "boysenberry",
            "lavender",
            "plum",
            "magenta",
            "lilac",
            "grape",
            "eggplant",
            "eggshell",
            "iris",
            "heather",
            "amethyst",
            "raisin",
            "orchid",
            "mulberry",
            "carbon",
            "slate",
            "sky",
            "navy",
            "indigo",
            "cobalt",
            "cedar",
            "ocean",
            "azure",
            "cerulean",
            "spruce",
            "stone",
            "aegean",
            "denim",
            "admiral",
            "sapphire",
            "arctic",
            "green",
            "chartreuse",
            "juniper",
            "sage",
            "lime",
            "fern",
            "olive",
            "emerald",
            "pear",
            "mossy",
            "shamrock",
            "seafoam",
            "pine",
            "mint",
            "seaweed",
            "pickle",
            "pistachio",
            "basil",
            "brown",
            "coffee",
            "chrome",
            "peanut",
            "carob",
            "hickory",
            "wooden",
            "pecan",
            "walnut",
            "caramel",
            "gingerbread",
            "syrup",
            "chocolate",
            "tortilla",
            "umber",
            "tawny",
            "brunette",
            "cinnamon",
            "glossy",
            "teal",
            "grey",
            "shadow",
            "graphite",
            "iron",
            "pewter",
            "cloud",
            "silver",
            "smoke",
            "gauze",
            "ash",
            "foggy",
            "flint",
            "charcoal",
            "pebble",
            "lead",
            "tin",
            "fossilized",
            "black",
            "ebony",
            "midnight",
            "inky",
            "oily",
            "satin",
            "onyx",
            "nylon",
            "fleece",
            "sable",
            "jetblack",
            "coal",
            "mocha",
            "obsidian",
            "jade",
            "cyan",
            "leather",
            "maroon",
            "carmine",
            "aqua",
            "chambray",
            "holographic",
            "laurel",
            "licorice",
            "khaki",
            "goldenrod",
            "malachite",
            "mandarin",
            "mango",
            "taupe",
            "aquamarine",
            "turquoise",
            "vermilion",
            "saffron",
            "cinnabar",
            "myrtle",
            "neon",
            "burgundy",
            "tangelo",
            "topaz",
            "wintergreen",
            "viridian",
            "vanilla",
            "paisley",
            "raspberry",
            "tweed",
            "pastel",
            "opal",
            "menthol",
            "champagne",
            "gunmetal",
            "infrared",
            "ultraviolet",
            "rainbow",
            "mercurial",
            "clear",
            "misty",
            "steel",
            "zinc",
            "citron",
            "cornflower",
            "lava",
            "quartz",
            "honeysuckle",
            "chili",
    };
    
    protected static final String animals[] = {
            "alligator",
            "bee",
            "bird",
            "camel",
            "cat",
            "cheetah",
            "chicken",
            "cow",
            "dog",
            "corgi",
            "eagle",
            "elephant",
            "fish",
            "fox",
            "toad",
            "giraffe",
            "hippo",
            "kangaroo",
            "kitten",
            "lobster",
            "monkey",
            "octopus",
            "pig",
            "puppy",
            "rabbit",
            "rat",
            "scorpion",
            "seal",
            "sheep",
            "snail",
            "spider",
            "tiger",
            "turtle",
            "newt",
            "tadpole",
            "frog",
            "tarantula",
            "albatross",
            "blackbird",
            "canary",
            "crow",
            "cuckoo",
            "dove",
            "pigeon",
            "falcon",
            "finch",
            "flamingo",
            "goose",
            "seagull",
            "hawk",
            "jay",
            "mockingbird",
            "kestrel",
            "kookaburra",
            "mallard",
            "nightingale",
            "nuthatch",
            "ostrich",
            "owl",
            "parakeet",
            "parrot",
            "peacock",
            "pelican",
            "penguin",
            "pheasant",
            "piranha",
            "raven",
            "robin",
            "rooster",
            "sparrow",
            "stork",
            "swallow",
            "swan",
            "swift",
            "turkey",
            "vulture",
            "woodpecker",
            "wren",
            "butterfly",
            "barbel",
            "carp",
            "cod",
            "crab",
            "eel",
            "goldfish",
            "haddock",
            "halibut",
            "jellyfish",
            "perch",
            "pike",
            "mantaray",
            "salmon",
            "sawfish",
            "scallop",
            "shark",
            "shell",
            "shrimp",
            "trout",
            "ant",
            "aphid",
            "beetle",
            "caterpillar",
            "dragonfly",
            "cricket",
            "fly",
            "grasshopper",
            "ladybug",
            "millipede",
            "moth",
            "wasp",
            "anteater",
            "antelope",
            "armadillo",
            "badger",
            "bat",
            "beaver",
            "bull",
            "chimpanzee",
            "dachshund",
            "deer",
            "dolphin",
            "elk",
            "moose",
            "gazelle",
            "gerbil",
            "goat",
            "bear",
            "hamster",
            "hare",
            "hedgehog",
            "horse",
            "hyena",
            "lion",
            "llama",
            "lynx",
            "mammoth",
            "marmot",
            "mink",
            "mole",
            "mongoose",
            "mouse",
            "mule",
            "otter",
            "panda",
            "platypus",
            "pony",
            "porcupine",
            "puma",
            "raccoon",
            "reindeer",
            "rhino",
            "skunk",
            "sloth",
            "squirrel",
            "weasel",
            "snake",
            "wolf",
            "zebra",
            "boa",
            "chameleon",
            "copperhead",
            "cottonmouth",
            "crocodile",
            "rattlesnake",
            "gecko",
            "iguana",
            "lizard",
            "python",
            "salamander",
            "sidewinder",
            "whale",
            "tortoise",
            "lemur",
            "rook",
            "koala",
            "donkey",
            "ferret",
            "tardigrade",
            "orca",
            "okapi",
            "liger",
            "unicorn",
            "dragon",
            "squid",
            "ape",
            "gorilla",
            "baboon",
            "cormorant",
            "mantis",
            "tapir",
            "capybara",
            "pangolin",
            "opossum",
            "wombat",
            "aardvark",
            "starfish",
            "shetland",
            "narwhal",
            "worm",
            "hornet",
            "viper",
            "stallion",
            "jaguar",
            "panther",
            "bobcat",
            "leopard",
            "osprey",
            "cougar",
            "dalmatian",
            "terrier",
            "duck",
            "sealion",
            "raccoon",
            "chipmunk",
            "loris",
            "poodle",
            "orangutan",
            "gibbon",
            "meerkat",
            "huskie",
            "barracuda",
            "bison",
            "caribou",
            "chinchilla",
            "coyote",
            "crane",
            "dinosaur",
            "lark",
            "griffin",
            "yeti",
            "troll",
            "seahorse",
            "walrus",
            "yak",
            "wolverine",
            "boar",
            "alpaca",
            "porpoise",
            "manatee",
            "guppy",
            "condor",
            "cyborg",
            "cobra",
            "locust",
            "mandrill",
            "oyster",
            "urchin",
            "quail",
            "sardine",
            "ram",
            "starling",
            "wallaby",
            "buffalo",
            "goblin",
            "tuna",
            "mustang"
    };

    protected static final String adjectives[] = {
            "attractive",
            "bald",
            "beautiful",
            "rare",
            "clean",
            "dazzling",
            "lucky",
            "elegant",
            "fancy",
            "fit",
            "fantastic",
            "glamorous",
            "gorgeous",
            "handsome",
            "long",
            "magnificent",
            "muscular",
            "plain",
            "able",
            "quaint",
            "scruffy",
            "innocent",
            "short",
            "skinny",
            "acrobatic",
            "tall",
            "proper",
            "alert",
            "lone",
            "agreeable",
            "ambitious",
            "brave",
            "calm",
            "delightful",
            "eager",
            "faithful",
            "gentle",
            "happy",
            "jolly",
            "kind",
            "lively",
            "nice",
            "obedient",
            "polite",
            "proud",
            "silly",
            "thankful",
            "winning",
            "witty",
            "wonderful",
            "zealous",
            "expert",
            "amateur",
            "clumsy",
            "amusing",
            "vast",
            "fierce",
            "real",
            "helpful",
            "itchy",
            "atomic",
            "basic",
            "mysterious",
            "blurry",
            "perfect",
            "best",
            "powerful",
            "interesting",
            "decent",
            "wild",
            "jovial",
            "genuine",
            "broad",
            "brisk",
            "brilliant",
            "curved",
            "deep",
            "flat",
            "high",
            "hollow",
            "low",
            "narrow",
            "refined",
            "round",
            "shallow",
            "skinny",
            "square",
            "steep",
            "straight",
            "wide",
            "big",
            "colossal",
            "clever",
            "gigantic",
            "great",
            "huge",
            "immense",
            "large",
            "little",
            "mammoth",
            "massive",
            "micro",
            "mini",
            "petite",
            "puny",
            "scrawny",
            "short",
            "small",
            "polished",
            "teeny",
            "tiny",
            "crazy",
            "dancing",
            "custom",
            "faint",
            "harsh",
            "formal",
            "howling",
            "loud",
            "melodic",
            "noisy",
            "upbeat",
            "quiet",
            "dandy",
            "raspy",
            "rhythmic",
            "daring",
            "zany",
            "digital",
            "dizzy",
            "exotic",
            "fun",
            "furry",
            "hidden",
            "ancient",
            "brief",
            "early",
            "fast",
            "future",
            "late",
            "long",
            "modern",
            "old",
            "prehistoric",
            "zesty",
            "rapid",
            "short",
            "slow",
            "swift",
            "young",
            "acidic",
            "bitter",
            "cool",
            "creamy",
            "keen",
            "tricky",
            "fresh",
            "special",
            "unique",
            "hot",
            "magic",
            "main",
            "nutty",
            "pet",
            "mythical",
            "ripe",
            "wobbly",
            "salty",
            "savory",
            "sour",
            "spicy",
            "bright",
            "stale",
            "sweet",
            "tangy",
            "tart",
            "rich",
            "rural",
            "urban",
            "breezy",
            "bumpy",
            "chilly",
            "cold",
            "cool",
            "cuddly",
            "damaged",
            "damp",
            "restless",
            "dry",
            "flaky",
            "fluffy",
            "virtual",
            "merry",
            "hot",
            "icy",
            "shiny",
            "melted",
            "joyous",
            "rough",
            "shaggy",
            "sharp",
            "radiant",
            "sticky",
            "strong",
            "soft",
            "uneven",
            "warm",
            "feisty",
            "cheery",
            "energetic",
            "abundant",
            "macho",
            "glorious",
            "mean",
            "quick",
            "precise",
            "stable",
            "spare",
            "sunny",
            "trendy",
            "shambolic",
            "striped",
            "boxy",
            "generous",
            "tame",
            "joyful",
            "festive",
            "bubbly",
            "soaring",
            "orbiting",
            "sparkly",
            "smooth",
            "docile",
            "original",
            "electric",
            "funny",
            "passive",
            "active",
            "cheesy",
            "tangy",
            "blunt",
            "dapper",
            "bent",
            "curly",
            "oblong",
            "sneaky",
            "overt",
            "careful",
            "jumpy",
            "bouncy",
            "recumbent",
            "cheerful",
            "droll",
            "odd",
            "suave",
            "sleepy"
    };

}
