{
 "title": "ETL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cache state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hotspot Cache Response Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(etl_hotspot_cache_total_time[1m])/increase(etl_hotspot_cache_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Cache Response Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(etl_beacon_cache_total_time[1m])/increase(etl_beacon_cache_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hotspot Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(etl_hotspot_cache_miss[1m])/increase(etl_hotspot_cache_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(etl_beacon_cache_miss[1m])/increase(etl_beacon_cache_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingestion Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Valid Witnesses",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(etl_witness_valid[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etl_file_processed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Beacon Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etl_file_beacon_distance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AWS Failure",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 10 },
   "targets": [
    { "expr": "increase(etl_aws_failure[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Witness Age",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etl_file_witness_distance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Files Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(etl_file_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witnesses Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "increase(etl_witness_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "increase(etl_beacon_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(etl_file_processed_time[$__rate_interval])/increase(etl_file_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Witness Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(etl_witness_processed_time[$__rate_interval])/increase(etl_witness_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(etl_beacon_processed_time[$__rate_interval])/increase(etl_beacon_processed[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}