global:
  scrape_interval: 10s
  external_labels:
    server: etl

scrape_configs:
  - job_name: etl
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8091']
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8093']
  - job_name: mongo
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8094']
        labels:
          node_name: mongoCluster
          service_name: mongo
          cluster: etlCluster
          replication_set: none
          service_type: mongos
