global:
  scrape_interval: 10s
  external_labels:
    server: etl

scrape_configs:
  - job_name: etl
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['etl:8091']
        labels:
          application: etl
          instance: local
  - job_name: node
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8093']
  - job_name: mongo
    scrape_interval: 5s
    static_configs:
      - targets: ['etl-mongo-exporter:9216']
        labels:
          node_name: mongoCluster
          service_name: mongo
          cluster: etlCluster
          replication_set: none
          service_type: mongos
