// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_lora.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc;

public interface gateway_rewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.gateway_reward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#47; Public key of the hotspot
   * </pre>
   *
   * <code>bytes hotspot_key = 1;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <pre>
   * &#47; Amount in iot bones credited to the hotspot for beaconing
   * </pre>
   *
   * <code>uint64 beacon_amount = 2;</code>
   * @return The beaconAmount.
   */
  long getBeaconAmount();

  /**
   * <pre>
   * &#47; Amount in iot bones credited to the hotspot for witnessing
   * </pre>
   *
   * <code>uint64 witness_amount = 3;</code>
   * @return The witnessAmount.
   */
  long getWitnessAmount();

  /**
   * <pre>
   * &#47; Amount in iot bones credited to the hotspot for data transfer
   * </pre>
   *
   * <code>uint64 dc_transfer_amount = 4;</code>
   * @return The dcTransferAmount.
   */
  long getDcTransferAmount();
}
