// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_lora.proto

package xyz.nova.grpc;

public interface gateway_reward_shareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.gateway_reward_share)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; Public key of the hotspot
   * </pre>
   *
   * <code>bytes hotspot_key = 1;</code>
   * @return The hotspotKey.
   */
  com.google.protobuf.ByteString getHotspotKey();

  /**
   * <pre>
   *&#47; Amount credited to the hotspot for beaconing
   * </pre>
   *
   * <code>uint64 beacon_amount = 2;</code>
   * @return The beaconAmount.
   */
  long getBeaconAmount();

  /**
   * <pre>
   *&#47; Amount credited to the hotspot for witnessing
   * </pre>
   *
   * <code>uint64 witness_amount = 3;</code>
   * @return The witnessAmount.
   */
  long getWitnessAmount();

  /**
   * <pre>
   *&#47; Unix timestamp in seconds of the start of the reward period
   * </pre>
   *
   * <code>uint64 start_period = 4;</code>
   * @return The startPeriod.
   */
  long getStartPeriod();

  /**
   * <pre>
   *&#47; Unix timestamp in seconds of the end of the reward period
   * </pre>
   *
   * <code>uint64 end_period = 5;</code>
   * @return The endPeriod.
   */
  long getEndPeriod();
}
