// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/packet_verifier.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc;

public interface invalid_packetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.packet_verifier.invalid_packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 payload_size = 1;</code>
   * @return The payloadSize.
   */
  int getPayloadSize();

  /**
   * <code>bytes gateway = 2;</code>
   * @return The gateway.
   */
  com.google.protobuf.ByteString getGateway();

  /**
   * <code>bytes payload_hash = 3;</code>
   * @return The payloadHash.
   */
  com.google.protobuf.ByteString getPayloadHash();

  /**
   * <code>.helium.packet_verifier.invalid_packet_reason reason = 4;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.helium.packet_verifier.invalid_packet_reason reason = 4;</code>
   * @return The reason.
   */
  com.helium.grpc.invalid_packet_reason getReason();
}
