// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_lora.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc;

public interface lora_stream_session_offer_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.lora_stream_session_offer_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes nonce = 1;</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();
}
