// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_lora.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc;

public interface lora_invalid_witness_report_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.lora_invalid_witness_report_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Timestamp at ingest in millis since unix epoch
   * </pre>
   *
   * <code>uint64 received_timestamp = 1;</code>
   * @return The receivedTimestamp.
   */
  long getReceivedTimestamp();

  /**
   * <code>.helium.poc_lora.invalid_reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.helium.poc_lora.invalid_reason reason = 2;</code>
   * @return The reason.
   */
  com.helium.grpc.invalid_reason getReason();

  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   * @return Whether the report field is set.
   */
  boolean hasReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   * @return The report.
   */
  com.helium.grpc.lora_witness_report_req_v1 getReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   */
  com.helium.grpc.lora_witness_report_req_v1OrBuilder getReportOrBuilder();

  /**
   * <pre>
   * the participant to which the reason applies,
   * which rendered the report as invalid
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_participant_side participant_side = 4;</code>
   * @return The enum numeric value on the wire for participantSide.
   */
  int getParticipantSideValue();
  /**
   * <pre>
   * the participant to which the reason applies,
   * which rendered the report as invalid
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_participant_side participant_side = 4;</code>
   * @return The participantSide.
   */
  com.helium.grpc.invalid_participant_side getParticipantSide();

  /**
   * <pre>
   * provides any additional context for invalid reason
   * for example the deny list version used as part of the deny list check
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_details invalid_details = 5;</code>
   * @return Whether the invalidDetails field is set.
   */
  boolean hasInvalidDetails();
  /**
   * <pre>
   * provides any additional context for invalid reason
   * for example the deny list version used as part of the deny list check
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_details invalid_details = 5;</code>
   * @return The invalidDetails.
   */
  com.helium.grpc.invalid_details getInvalidDetails();
  /**
   * <pre>
   * provides any additional context for invalid reason
   * for example the deny list version used as part of the deny list check
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_details invalid_details = 5;</code>
   */
  com.helium.grpc.invalid_detailsOrBuilder getInvalidDetailsOrBuilder();
}
