// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_lora.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc;

/**
 * Protobuf type {@code helium.poc_lora.lora_stream_request_v1}
 */
public final class lora_stream_request_v1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helium.poc_lora.lora_stream_request_v1)
    lora_stream_request_v1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use lora_stream_request_v1.newBuilder() to construct.
  private lora_stream_request_v1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lora_stream_request_v1() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new lora_stream_request_v1();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.PocLoRa.internal_static_helium_poc_lora_lora_stream_request_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.PocLoRa.internal_static_helium_poc_lora_lora_stream_request_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.lora_stream_request_v1.class, com.helium.grpc.lora_stream_request_v1.Builder.class);
  }

  private int requestCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BEACON_REPORT(1),
    WITNESS_REPORT(2),
    SESSION_INIT(3),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return BEACON_REPORT;
        case 2: return WITNESS_REPORT;
        case 3: return SESSION_INIT;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int BEACON_REPORT_FIELD_NUMBER = 1;
  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   * @return Whether the beaconReport field is set.
   */
  @java.lang.Override
  public boolean hasBeaconReport() {
    return requestCase_ == 1;
  }
  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   * @return The beaconReport.
   */
  @java.lang.Override
  public com.helium.grpc.lora_beacon_report_req_v1 getBeaconReport() {
    if (requestCase_ == 1) {
       return (com.helium.grpc.lora_beacon_report_req_v1) request_;
    }
    return com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
  }
  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   */
  @java.lang.Override
  public com.helium.grpc.lora_beacon_report_req_v1OrBuilder getBeaconReportOrBuilder() {
    if (requestCase_ == 1) {
       return (com.helium.grpc.lora_beacon_report_req_v1) request_;
    }
    return com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
  }

  public static final int WITNESS_REPORT_FIELD_NUMBER = 2;
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   * @return Whether the witnessReport field is set.
   */
  @java.lang.Override
  public boolean hasWitnessReport() {
    return requestCase_ == 2;
  }
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   * @return The witnessReport.
   */
  @java.lang.Override
  public com.helium.grpc.lora_witness_report_req_v1 getWitnessReport() {
    if (requestCase_ == 2) {
       return (com.helium.grpc.lora_witness_report_req_v1) request_;
    }
    return com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
  }
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   */
  @java.lang.Override
  public com.helium.grpc.lora_witness_report_req_v1OrBuilder getWitnessReportOrBuilder() {
    if (requestCase_ == 2) {
       return (com.helium.grpc.lora_witness_report_req_v1) request_;
    }
    return com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
  }

  public static final int SESSION_INIT_FIELD_NUMBER = 3;
  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   * @return Whether the sessionInit field is set.
   */
  @java.lang.Override
  public boolean hasSessionInit() {
    return requestCase_ == 3;
  }
  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   * @return The sessionInit.
   */
  @java.lang.Override
  public com.helium.grpc.lora_stream_session_init_v1 getSessionInit() {
    if (requestCase_ == 3) {
       return (com.helium.grpc.lora_stream_session_init_v1) request_;
    }
    return com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
  }
  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   */
  @java.lang.Override
  public com.helium.grpc.lora_stream_session_init_v1OrBuilder getSessionInitOrBuilder() {
    if (requestCase_ == 3) {
       return (com.helium.grpc.lora_stream_session_init_v1) request_;
    }
    return com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.helium.grpc.lora_beacon_report_req_v1) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (com.helium.grpc.lora_witness_report_req_v1) request_);
    }
    if (requestCase_ == 3) {
      output.writeMessage(3, (com.helium.grpc.lora_stream_session_init_v1) request_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.helium.grpc.lora_beacon_report_req_v1) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.helium.grpc.lora_witness_report_req_v1) request_);
    }
    if (requestCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.helium.grpc.lora_stream_session_init_v1) request_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.lora_stream_request_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.lora_stream_request_v1 other = (com.helium.grpc.lora_stream_request_v1) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getBeaconReport()
            .equals(other.getBeaconReport())) return false;
        break;
      case 2:
        if (!getWitnessReport()
            .equals(other.getWitnessReport())) return false;
        break;
      case 3:
        if (!getSessionInit()
            .equals(other.getSessionInit())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + BEACON_REPORT_FIELD_NUMBER;
        hash = (53 * hash) + getBeaconReport().hashCode();
        break;
      case 2:
        hash = (37 * hash) + WITNESS_REPORT_FIELD_NUMBER;
        hash = (53 * hash) + getWitnessReport().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SESSION_INIT_FIELD_NUMBER;
        hash = (53 * hash) + getSessionInit().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.helium.grpc.lora_stream_request_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.helium.grpc.lora_stream_request_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.lora_stream_request_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.lora_stream_request_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.poc_lora.lora_stream_request_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.poc_lora.lora_stream_request_v1)
      com.helium.grpc.lora_stream_request_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.PocLoRa.internal_static_helium_poc_lora_lora_stream_request_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.PocLoRa.internal_static_helium_poc_lora_lora_stream_request_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.lora_stream_request_v1.class, com.helium.grpc.lora_stream_request_v1.Builder.class);
    }

    // Construct using com.helium.grpc.lora_stream_request_v1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (beaconReportBuilder_ != null) {
        beaconReportBuilder_.clear();
      }
      if (witnessReportBuilder_ != null) {
        witnessReportBuilder_.clear();
      }
      if (sessionInitBuilder_ != null) {
        sessionInitBuilder_.clear();
      }
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.PocLoRa.internal_static_helium_poc_lora_lora_stream_request_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.lora_stream_request_v1 getDefaultInstanceForType() {
      return com.helium.grpc.lora_stream_request_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.lora_stream_request_v1 build() {
      com.helium.grpc.lora_stream_request_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.lora_stream_request_v1 buildPartial() {
      com.helium.grpc.lora_stream_request_v1 result = new com.helium.grpc.lora_stream_request_v1(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.helium.grpc.lora_stream_request_v1 result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.helium.grpc.lora_stream_request_v1 result) {
      result.requestCase_ = requestCase_;
      result.request_ = this.request_;
      if (requestCase_ == 1 &&
          beaconReportBuilder_ != null) {
        result.request_ = beaconReportBuilder_.build();
      }
      if (requestCase_ == 2 &&
          witnessReportBuilder_ != null) {
        result.request_ = witnessReportBuilder_.build();
      }
      if (requestCase_ == 3 &&
          sessionInitBuilder_ != null) {
        result.request_ = sessionInitBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.lora_stream_request_v1) {
        return mergeFrom((com.helium.grpc.lora_stream_request_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.lora_stream_request_v1 other) {
      if (other == com.helium.grpc.lora_stream_request_v1.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case BEACON_REPORT: {
          mergeBeaconReport(other.getBeaconReport());
          break;
        }
        case WITNESS_REPORT: {
          mergeWitnessReport(other.getWitnessReport());
          break;
        }
        case SESSION_INIT: {
          mergeSessionInit(other.getSessionInit());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBeaconReportFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getWitnessReportFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSessionInitFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_beacon_report_req_v1, com.helium.grpc.lora_beacon_report_req_v1.Builder, com.helium.grpc.lora_beacon_report_req_v1OrBuilder> beaconReportBuilder_;
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     * @return Whether the beaconReport field is set.
     */
    @java.lang.Override
    public boolean hasBeaconReport() {
      return requestCase_ == 1;
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     * @return The beaconReport.
     */
    @java.lang.Override
    public com.helium.grpc.lora_beacon_report_req_v1 getBeaconReport() {
      if (beaconReportBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.helium.grpc.lora_beacon_report_req_v1) request_;
        }
        return com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return beaconReportBuilder_.getMessage();
        }
        return com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    public Builder setBeaconReport(com.helium.grpc.lora_beacon_report_req_v1 value) {
      if (beaconReportBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        beaconReportBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    public Builder setBeaconReport(
        com.helium.grpc.lora_beacon_report_req_v1.Builder builderForValue) {
      if (beaconReportBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        beaconReportBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    public Builder mergeBeaconReport(com.helium.grpc.lora_beacon_report_req_v1 value) {
      if (beaconReportBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance()) {
          request_ = com.helium.grpc.lora_beacon_report_req_v1.newBuilder((com.helium.grpc.lora_beacon_report_req_v1) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          beaconReportBuilder_.mergeFrom(value);
        } else {
          beaconReportBuilder_.setMessage(value);
        }
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    public Builder clearBeaconReport() {
      if (beaconReportBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        beaconReportBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    public com.helium.grpc.lora_beacon_report_req_v1.Builder getBeaconReportBuilder() {
      return getBeaconReportFieldBuilder().getBuilder();
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    @java.lang.Override
    public com.helium.grpc.lora_beacon_report_req_v1OrBuilder getBeaconReportOrBuilder() {
      if ((requestCase_ == 1) && (beaconReportBuilder_ != null)) {
        return beaconReportBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.helium.grpc.lora_beacon_report_req_v1) request_;
        }
        return com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_beacon_report_req_v1, com.helium.grpc.lora_beacon_report_req_v1.Builder, com.helium.grpc.lora_beacon_report_req_v1OrBuilder> 
        getBeaconReportFieldBuilder() {
      if (beaconReportBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.helium.grpc.lora_beacon_report_req_v1.getDefaultInstance();
        }
        beaconReportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.helium.grpc.lora_beacon_report_req_v1, com.helium.grpc.lora_beacon_report_req_v1.Builder, com.helium.grpc.lora_beacon_report_req_v1OrBuilder>(
                (com.helium.grpc.lora_beacon_report_req_v1) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();
      return beaconReportBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_witness_report_req_v1, com.helium.grpc.lora_witness_report_req_v1.Builder, com.helium.grpc.lora_witness_report_req_v1OrBuilder> witnessReportBuilder_;
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     * @return Whether the witnessReport field is set.
     */
    @java.lang.Override
    public boolean hasWitnessReport() {
      return requestCase_ == 2;
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     * @return The witnessReport.
     */
    @java.lang.Override
    public com.helium.grpc.lora_witness_report_req_v1 getWitnessReport() {
      if (witnessReportBuilder_ == null) {
        if (requestCase_ == 2) {
          return (com.helium.grpc.lora_witness_report_req_v1) request_;
        }
        return com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return witnessReportBuilder_.getMessage();
        }
        return com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    public Builder setWitnessReport(com.helium.grpc.lora_witness_report_req_v1 value) {
      if (witnessReportBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        witnessReportBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    public Builder setWitnessReport(
        com.helium.grpc.lora_witness_report_req_v1.Builder builderForValue) {
      if (witnessReportBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        witnessReportBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    public Builder mergeWitnessReport(com.helium.grpc.lora_witness_report_req_v1 value) {
      if (witnessReportBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance()) {
          request_ = com.helium.grpc.lora_witness_report_req_v1.newBuilder((com.helium.grpc.lora_witness_report_req_v1) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          witnessReportBuilder_.mergeFrom(value);
        } else {
          witnessReportBuilder_.setMessage(value);
        }
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    public Builder clearWitnessReport() {
      if (witnessReportBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        witnessReportBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    public com.helium.grpc.lora_witness_report_req_v1.Builder getWitnessReportBuilder() {
      return getWitnessReportFieldBuilder().getBuilder();
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    @java.lang.Override
    public com.helium.grpc.lora_witness_report_req_v1OrBuilder getWitnessReportOrBuilder() {
      if ((requestCase_ == 2) && (witnessReportBuilder_ != null)) {
        return witnessReportBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (com.helium.grpc.lora_witness_report_req_v1) request_;
        }
        return com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_witness_report_req_v1, com.helium.grpc.lora_witness_report_req_v1.Builder, com.helium.grpc.lora_witness_report_req_v1OrBuilder> 
        getWitnessReportFieldBuilder() {
      if (witnessReportBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = com.helium.grpc.lora_witness_report_req_v1.getDefaultInstance();
        }
        witnessReportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.helium.grpc.lora_witness_report_req_v1, com.helium.grpc.lora_witness_report_req_v1.Builder, com.helium.grpc.lora_witness_report_req_v1OrBuilder>(
                (com.helium.grpc.lora_witness_report_req_v1) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();
      return witnessReportBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_stream_session_init_v1, com.helium.grpc.lora_stream_session_init_v1.Builder, com.helium.grpc.lora_stream_session_init_v1OrBuilder> sessionInitBuilder_;
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     * @return Whether the sessionInit field is set.
     */
    @java.lang.Override
    public boolean hasSessionInit() {
      return requestCase_ == 3;
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     * @return The sessionInit.
     */
    @java.lang.Override
    public com.helium.grpc.lora_stream_session_init_v1 getSessionInit() {
      if (sessionInitBuilder_ == null) {
        if (requestCase_ == 3) {
          return (com.helium.grpc.lora_stream_session_init_v1) request_;
        }
        return com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
      } else {
        if (requestCase_ == 3) {
          return sessionInitBuilder_.getMessage();
        }
        return com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    public Builder setSessionInit(com.helium.grpc.lora_stream_session_init_v1 value) {
      if (sessionInitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        sessionInitBuilder_.setMessage(value);
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    public Builder setSessionInit(
        com.helium.grpc.lora_stream_session_init_v1.Builder builderForValue) {
      if (sessionInitBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        sessionInitBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    public Builder mergeSessionInit(com.helium.grpc.lora_stream_session_init_v1 value) {
      if (sessionInitBuilder_ == null) {
        if (requestCase_ == 3 &&
            request_ != com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance()) {
          request_ = com.helium.grpc.lora_stream_session_init_v1.newBuilder((com.helium.grpc.lora_stream_session_init_v1) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 3) {
          sessionInitBuilder_.mergeFrom(value);
        } else {
          sessionInitBuilder_.setMessage(value);
        }
      }
      requestCase_ = 3;
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    public Builder clearSessionInit() {
      if (sessionInitBuilder_ == null) {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 3) {
          requestCase_ = 0;
          request_ = null;
        }
        sessionInitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    public com.helium.grpc.lora_stream_session_init_v1.Builder getSessionInitBuilder() {
      return getSessionInitFieldBuilder().getBuilder();
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    @java.lang.Override
    public com.helium.grpc.lora_stream_session_init_v1OrBuilder getSessionInitOrBuilder() {
      if ((requestCase_ == 3) && (sessionInitBuilder_ != null)) {
        return sessionInitBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 3) {
          return (com.helium.grpc.lora_stream_session_init_v1) request_;
        }
        return com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
      }
    }
    /**
     * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.helium.grpc.lora_stream_session_init_v1, com.helium.grpc.lora_stream_session_init_v1.Builder, com.helium.grpc.lora_stream_session_init_v1OrBuilder> 
        getSessionInitFieldBuilder() {
      if (sessionInitBuilder_ == null) {
        if (!(requestCase_ == 3)) {
          request_ = com.helium.grpc.lora_stream_session_init_v1.getDefaultInstance();
        }
        sessionInitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.helium.grpc.lora_stream_session_init_v1, com.helium.grpc.lora_stream_session_init_v1.Builder, com.helium.grpc.lora_stream_session_init_v1OrBuilder>(
                (com.helium.grpc.lora_stream_session_init_v1) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 3;
      onChanged();
      return sessionInitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helium.poc_lora.lora_stream_request_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.poc_lora.lora_stream_request_v1)
  private static final com.helium.grpc.lora_stream_request_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.lora_stream_request_v1();
  }

  public static com.helium.grpc.lora_stream_request_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lora_stream_request_v1>
      PARSER = new com.google.protobuf.AbstractParser<lora_stream_request_v1>() {
    @java.lang.Override
    public lora_stream_request_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<lora_stream_request_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lora_stream_request_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.lora_stream_request_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

