// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/poc_lora.proto
// Protobuf Java Version: 4.29.2

package com.helium.grpc;

public interface lora_stream_request_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.lora_stream_request_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   * @return Whether the beaconReport field is set.
   */
  boolean hasBeaconReport();
  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   * @return The beaconReport.
   */
  com.helium.grpc.lora_beacon_report_req_v1 getBeaconReport();
  /**
   * <code>.helium.poc_lora.lora_beacon_report_req_v1 beacon_report = 1;</code>
   */
  com.helium.grpc.lora_beacon_report_req_v1OrBuilder getBeaconReportOrBuilder();

  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   * @return Whether the witnessReport field is set.
   */
  boolean hasWitnessReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   * @return The witnessReport.
   */
  com.helium.grpc.lora_witness_report_req_v1 getWitnessReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 witness_report = 2;</code>
   */
  com.helium.grpc.lora_witness_report_req_v1OrBuilder getWitnessReportOrBuilder();

  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   * @return Whether the sessionInit field is set.
   */
  boolean hasSessionInit();
  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   * @return The sessionInit.
   */
  com.helium.grpc.lora_stream_session_init_v1 getSessionInit();
  /**
   * <code>.helium.poc_lora.lora_stream_session_init_v1 session_init = 3;</code>
   */
  com.helium.grpc.lora_stream_session_init_v1OrBuilder getSessionInitOrBuilder();

  com.helium.grpc.lora_stream_request_v1.RequestCase getRequestCase();
}
