// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_lora.proto

package xyz.nova.grpc;

public interface lora_verified_witness_report_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.lora_verified_witness_report_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Timestamp at ingest in millis since unix epoch
   * </pre>
   *
   * <code>uint64 received_timestamp = 1;</code>
   * @return The receivedTimestamp.
   */
  long getReceivedTimestamp();

  /**
   * <code>.helium.poc_lora.verification_status status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.helium.poc_lora.verification_status status = 2;</code>
   * @return The status.
   */
  xyz.nova.grpc.verification_status getStatus();

  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   * @return Whether the report field is set.
   */
  boolean hasReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   * @return The report.
   */
  xyz.nova.grpc.lora_witness_report_req_v1 getReport();
  /**
   * <code>.helium.poc_lora.lora_witness_report_req_v1 report = 3;</code>
   */
  xyz.nova.grpc.lora_witness_report_req_v1OrBuilder getReportOrBuilder();

  /**
   * <code>string location = 4;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 4;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>uint32 hex_scale = 5;</code>
   * @return The hexScale.
   */
  int getHexScale();

  /**
   * <pre>
   * integer representation of a 4-point precision decimal multiplier
   * based on the number of witnesses to a poc event
   * </pre>
   *
   * <code>uint32 reward_unit = 6;</code>
   * @return The rewardUnit.
   */
  int getRewardUnit();

  /**
   * <code>.helium.poc_lora.invalid_reason invalid_reason = 7;</code>
   * @return The enum numeric value on the wire for invalidReason.
   */
  int getInvalidReasonValue();
  /**
   * <code>.helium.poc_lora.invalid_reason invalid_reason = 7;</code>
   * @return The invalidReason.
   */
  xyz.nova.grpc.invalid_reason getInvalidReason();

  /**
   * <pre>
   * the participant to which the reason applies,
   * which rendered the report as invalid
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_participant_side participant_side = 8;</code>
   * @return The enum numeric value on the wire for participantSide.
   */
  int getParticipantSideValue();
  /**
   * <pre>
   * the participant to which the reason applies,
   * which rendered the report as invalid
   * </pre>
   *
   * <code>.helium.poc_lora.invalid_participant_side participant_side = 8;</code>
   * @return The participantSide.
   */
  xyz.nova.grpc.invalid_participant_side getParticipantSide();
}
