// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/poc_lora.proto

package com.helium.grpc;

public interface operational_rewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.poc_lora.operational_reward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; Amount in iot bones credited to the operational fund wallet
   * </pre>
   *
   * <code>uint64 amount = 1;</code>
   * @return The amount.
   */
  long getAmount();
}
