// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/packet_verifier.proto

package com.helium.grpc;

/**
 * Protobuf type {@code helium.packet_verifier.valid_packet}
 */
public final class valid_packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helium.packet_verifier.valid_packet)
    valid_packetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use valid_packet.newBuilder() to construct.
  private valid_packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private valid_packet() {
    gateway_ = com.google.protobuf.ByteString.EMPTY;
    payloadHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new valid_packet();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PacketVerifier.internal_static_helium_packet_verifier_valid_packet_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PacketVerifier.internal_static_helium_packet_verifier_valid_packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            valid_packet.class, Builder.class);
  }

  public static final int PAYLOAD_SIZE_FIELD_NUMBER = 1;
  private int payloadSize_ = 0;
  /**
   * <code>uint32 payload_size = 1;</code>
   * @return The payloadSize.
   */
  @Override
  public int getPayloadSize() {
    return payloadSize_;
  }

  public static final int GATEWAY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString gateway_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes gateway = 2;</code>
   * @return The gateway.
   */
  @Override
  public com.google.protobuf.ByteString getGateway() {
    return gateway_;
  }

  public static final int PAYLOAD_HASH_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString payloadHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes payload_hash = 3;</code>
   * @return The payloadHash.
   */
  @Override
  public com.google.protobuf.ByteString getPayloadHash() {
    return payloadHash_;
  }

  public static final int NUM_DCS_FIELD_NUMBER = 4;
  private int numDcs_ = 0;
  /**
   * <code>uint32 num_dcs = 4;</code>
   * @return The numDcs.
   */
  @Override
  public int getNumDcs() {
    return numDcs_;
  }

  public static final int PACKET_TIMESTAMP_FIELD_NUMBER = 5;
  private long packetTimestamp_ = 0L;
  /**
   * <code>uint64 packet_timestamp = 5;</code>
   * @return The packetTimestamp.
   */
  @Override
  public long getPacketTimestamp() {
    return packetTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadSize_ != 0) {
      output.writeUInt32(1, payloadSize_);
    }
    if (!gateway_.isEmpty()) {
      output.writeBytes(2, gateway_);
    }
    if (!payloadHash_.isEmpty()) {
      output.writeBytes(3, payloadHash_);
    }
    if (numDcs_ != 0) {
      output.writeUInt32(4, numDcs_);
    }
    if (packetTimestamp_ != 0L) {
      output.writeUInt64(5, packetTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, payloadSize_);
    }
    if (!gateway_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, gateway_);
    }
    if (!payloadHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, payloadHash_);
    }
    if (numDcs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, numDcs_);
    }
    if (packetTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, packetTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof valid_packet)) {
      return super.equals(obj);
    }
    valid_packet other = (valid_packet) obj;

    if (getPayloadSize()
        != other.getPayloadSize()) return false;
    if (!getGateway()
        .equals(other.getGateway())) return false;
    if (!getPayloadHash()
        .equals(other.getPayloadHash())) return false;
    if (getNumDcs()
        != other.getNumDcs()) return false;
    if (getPacketTimestamp()
        != other.getPacketTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAYLOAD_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPayloadSize();
    hash = (37 * hash) + GATEWAY_FIELD_NUMBER;
    hash = (53 * hash) + getGateway().hashCode();
    hash = (37 * hash) + PAYLOAD_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getPayloadHash().hashCode();
    hash = (37 * hash) + NUM_DCS_FIELD_NUMBER;
    hash = (53 * hash) + getNumDcs();
    hash = (37 * hash) + PACKET_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static valid_packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static valid_packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static valid_packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static valid_packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static valid_packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static valid_packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static valid_packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static valid_packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static valid_packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static valid_packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static valid_packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static valid_packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(valid_packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.packet_verifier.valid_packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.packet_verifier.valid_packet)
      valid_packetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PacketVerifier.internal_static_helium_packet_verifier_valid_packet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PacketVerifier.internal_static_helium_packet_verifier_valid_packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              valid_packet.class, Builder.class);
    }

    // Construct using com.helium.grpc.valid_packet.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      payloadSize_ = 0;
      gateway_ = com.google.protobuf.ByteString.EMPTY;
      payloadHash_ = com.google.protobuf.ByteString.EMPTY;
      numDcs_ = 0;
      packetTimestamp_ = 0L;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PacketVerifier.internal_static_helium_packet_verifier_valid_packet_descriptor;
    }

    @Override
    public valid_packet getDefaultInstanceForType() {
      return valid_packet.getDefaultInstance();
    }

    @Override
    public valid_packet build() {
      valid_packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public valid_packet buildPartial() {
      valid_packet result = new valid_packet(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(valid_packet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.payloadSize_ = payloadSize_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gateway_ = gateway_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.payloadHash_ = payloadHash_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.numDcs_ = numDcs_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.packetTimestamp_ = packetTimestamp_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof valid_packet) {
        return mergeFrom((valid_packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(valid_packet other) {
      if (other == valid_packet.getDefaultInstance()) return this;
      if (other.getPayloadSize() != 0) {
        setPayloadSize(other.getPayloadSize());
      }
      if (other.getGateway() != com.google.protobuf.ByteString.EMPTY) {
        setGateway(other.getGateway());
      }
      if (other.getPayloadHash() != com.google.protobuf.ByteString.EMPTY) {
        setPayloadHash(other.getPayloadHash());
      }
      if (other.getNumDcs() != 0) {
        setNumDcs(other.getNumDcs());
      }
      if (other.getPacketTimestamp() != 0L) {
        setPacketTimestamp(other.getPacketTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              payloadSize_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              gateway_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              payloadHash_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              numDcs_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              packetTimestamp_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int payloadSize_ ;
    /**
     * <code>uint32 payload_size = 1;</code>
     * @return The payloadSize.
     */
    @Override
    public int getPayloadSize() {
      return payloadSize_;
    }
    /**
     * <code>uint32 payload_size = 1;</code>
     * @param value The payloadSize to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadSize(int value) {

      payloadSize_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 payload_size = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      payloadSize_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString gateway_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes gateway = 2;</code>
     * @return The gateway.
     */
    @Override
    public com.google.protobuf.ByteString getGateway() {
      return gateway_;
    }
    /**
     * <code>bytes gateway = 2;</code>
     * @param value The gateway to set.
     * @return This builder for chaining.
     */
    public Builder setGateway(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      gateway_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes gateway = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGateway() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gateway_ = getDefaultInstance().getGateway();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payloadHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload_hash = 3;</code>
     * @return The payloadHash.
     */
    @Override
    public com.google.protobuf.ByteString getPayloadHash() {
      return payloadHash_;
    }
    /**
     * <code>bytes payload_hash = 3;</code>
     * @param value The payloadHash to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payloadHash_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload_hash = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadHash() {
      bitField0_ = (bitField0_ & ~0x00000004);
      payloadHash_ = getDefaultInstance().getPayloadHash();
      onChanged();
      return this;
    }

    private int numDcs_ ;
    /**
     * <code>uint32 num_dcs = 4;</code>
     * @return The numDcs.
     */
    @Override
    public int getNumDcs() {
      return numDcs_;
    }
    /**
     * <code>uint32 num_dcs = 4;</code>
     * @param value The numDcs to set.
     * @return This builder for chaining.
     */
    public Builder setNumDcs(int value) {

      numDcs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 num_dcs = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumDcs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      numDcs_ = 0;
      onChanged();
      return this;
    }

    private long packetTimestamp_ ;
    /**
     * <code>uint64 packet_timestamp = 5;</code>
     * @return The packetTimestamp.
     */
    @Override
    public long getPacketTimestamp() {
      return packetTimestamp_;
    }
    /**
     * <code>uint64 packet_timestamp = 5;</code>
     * @param value The packetTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setPacketTimestamp(long value) {

      packetTimestamp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 packet_timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      packetTimestamp_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helium.packet_verifier.valid_packet)
  }

  // @@protoc_insertion_point(class_scope:helium.packet_verifier.valid_packet)
  private static final valid_packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new valid_packet();
  }

  public static valid_packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<valid_packet>
      PARSER = new com.google.protobuf.AbstractParser<valid_packet>() {
    @Override
    public valid_packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<valid_packet> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<valid_packet> getParserForType() {
    return PARSER;
  }

  @Override
  public valid_packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

